In [104]:
import pandas as pd

In [105]:
data=pd.read_csv('imdb_data (1).csv')

In [106]:
data.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [107]:
data.describe()

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [109]:
data.shape

(3000, 23)

In [110]:
data

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [111]:
data.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

#question 1: Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [112]:
df1=data.dropna(subset=['cast', 'crew']).reset_index(drop=True)

In [113]:
profit_data1=pd.DataFrame(df1['revenue']-df1['budget'],columns=['profit'])     #so this is the row which has max revenue we will analyse it more

In [114]:
profit_data1

         profit
0      -1685349
1      55149435
2       9792000
3      14800000
4       3923970
...         ...
2979    1596687
2980     180590
2981   24456761
2982  129963386
2983   47087155

[2984 rows x 1 columns]

In [115]:
max_profit=profit_data1['profit'].sort_values(ascending=False)

In [116]:
max_profit

1754    1316249360
1121    1299557910
2756    1125403694
681     1102886337
2312     928746996
           ...
176      -75171919
773      -80445998
307      -85321445
251      -87982678
2269     -92896027
Name: profit, Length: 2984, dtype: int64

In [117]:
max_p=max_profit.idxmax()          #max profit index

In [118]:
df1.loc[max_p,'cast']

'[{\'cast_id\': 17, \'character\': \'Dominic Toretto\', \'credit_id\': \'5431dfd10e0a265915002c34\', \'gender\': 2, \'id\': 12835, \'name\': \'Vin Diesel\', \'order\': 0, \'profile_path\': \'/7rwSXluNWZAluYMOEWBxkPmckES.jpg\'}, {\'cast_id\': 19, \'character\': "Brian O\'Conner", \'credit_id\': \'5431dfe4c3a3681143002b98\', \'gender\': 2, \'id\': 8167, \'name\': \'Paul Walker\', \'order\': 1, \'profile_path\': \'/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg\'}, {\'cast_id\': 18, \'character\': \'Hobbs\', \'credit_id\': \'5431dfdbc3a36831a6004376\', \'gender\': 2, \'id\': 18918, \'name\': \'Dwayne Johnson\', \'order\': 2, \'profile_path\': \'/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg\'}, {\'cast_id\': 20, \'character\': \'Letty\', \'credit_id\': \'5431dfeec3a36811ef002c75\', \'gender\': 1, \'id\': 17647, \'name\': \'Michelle Rodriguez\', \'order\': 3, \'profile_path\': \'/v37VK0MNuRuJOCKPKJcZAJXRA5r.jpg\'}, {\'cast_id\': 28, \'character\': \'Roman\', \'credit_id\': \'5431e0310e0a2656e2002c95\', \'gender\': 2, \'id\': 8169, \'name\': \'Tyrese Gibson\', \'order\': 4, \'profile_path\': \'/a3tyF7QXgeEH0QuEuIzNZZ8oLNS.jpg\'}, {\'cast_id\': 31, \'character\': "Tej (as Chris \'Ludacris\' Bridges)", \'credit_id\': \'5431e0520e0a2658b2002c3c\', \'gender\': 2, \'id\': 8171, \'name\': \'Ludacris\', \'order\': 5, \'profile_path\': \'/xLfq9wFO6dtYuUK96hbJ8I8EKFw.jpg\'}, {\'cast_id\': 24, \'character\': \'Mia\', \'credit_id\': \'5431e00dc3a36811ef002c7e\', \'gender\': 1, \'id\': 22123, \'name\': \'Jordana Brewster\', \'order\': 6, \'profile_path\': \'/dORwXZWWmDgG66I5i2Fnr27g3fO.jpg\'}, {\'cast_id\': 25, \'character\': \'Jakande\', \'credit_id\': \'5431e015c3a36831a90040da\', \'gender\': 2, \'id\': 938, \'name\': \'Djimon Hounsou\', \'order\': 7, \'profile_path\': \'/y22Pb0XAVqC0l7ukzKKtXzPEuHk.jpg\'}, {\'cast_id\': 30, \'character\': \'Kiet\', \'credit_id\': \'5431e04a0e0a26464300432c\', \'gender\': 2, \'id\': 57207, \'name\': \'Tony Jaa\', \'order\': 8, \'profile_path\': \'/qq0uXKe3aKaAE04QQ0BvbbFFufF.jpg\'}, {\'cast_id\': 21, \'character\': \'Kara\', \'credit_id\': \'5431dff40e0a2646490043fa\', \'gender\': 0, \'id\': 997887, \'name\': \'Ronda Rousey\', \'order\': 9, \'profile_path\': \'/5eGHTV1bLOdajC4Z3pnIdSiptSG.jpg\'}, {\'cast_id\': 27, \'character\': \'Ramsey\', \'credit_id\': \'5431e026c3a36831ac004333\', \'gender\': 1, \'id\': 1251069, \'name\': \'Nathalie Emmanuel\', \'order\': 10, \'profile_path\': \'/yYiJwunH04doOZJgMu7qTZyrRYJ.jpg\'}, {\'cast_id\': 22, \'character\': \'Mr. Nobody\', \'credit_id\': \'5431dffa0e0a265872002bdf\', \'gender\': 2, \'id\': 6856, \'name\': \'Kurt Russell\', \'order\': 11, \'profile_path\': \'/rlnFuNkisPpuypARI7QaGCmOY6V.jpg\'}, {\'cast_id\': 16, \'character\': \'Deckard Shaw\', \'credit_id\': \'5431dfc70e0a265872002bd5\', \'gender\': 2, \'id\': 976, \'name\': \'Jason Statham\', \'order\': 12, \'profile_path\': \'/PhWiWgasncGWD9LdbsGcmxkV4r.jpg\'}, {\'cast_id\': 39, \'character\': \'Han\', \'credit_id\': \'554fa75f92514110bd002a7d\', \'gender\': 2, \'id\': 61697, \'name\': \'Sung Kang\', \'order\': 13, \'profile_path\': \'/fqt53KEfHWsRDcbV2YAY2lKlKrM.jpg\'}, {\'cast_id\': 38, \'character\': \'Gisele\', \'credit_id\': \'554fa7439251413e40005aa1\', \'gender\': 1, \'id\': 90633, \'name\': \'Gal Gadot\', \'order\': 14, \'profile_path\': \'/34kHAyBaBhq2kUrmhM15paEBuuI.jpg\'}, {\'cast_id\': 15, \'character\': \'Sean Boswell\', \'credit_id\': \'5431dfbb0e0a265915002c2d\', \'gender\': 2, \'id\': 155, \'name\': \'Lucas Black\', \'order\': 15, \'profile_path\': \'/41qZZc6vRVm5ZOoXWfEf5NGoIZR.jpg\'}, {\'cast_id\': 23, \'character\': \'Elena\', \'credit_id\': \'5431e003c3a36811ef002c7c\', \'gender\': 1, \'id\': 73269, \'name\': \'Elsa Pataky\', \'order\': 16, \'profile_path\': \'/c1km2kqasJT9GTISMbBZpp3jbuR.jpg\'}, {\'cast_id\': 35, \'character\': \'Hector\', \'credit_id\': \'554fa677c3a3687b7d002468\', \'gender\': 2, \'id\': 53252, \'name\': \'Noel Gugliemi\', \'order\': 17, \'profile_path\': \'/mI5urNyZJAzIGxelTjBkm624DkB.jpg\'}, {\'cast_id\': 37, \'character\': \'Sheppard\', \'credit_id\': \'554fa6f19251413ea10004fc\', \'gender\': 2, \'id\': 222906, \'name\': \'John Brotherton\', \'order\': 18, \'profile_path\': \'/sE73Zs4q8rugmrFnn9jv2wAEVrI.jpg\'}, {\'cast_id\': 34, \'character\': \'Owen Shaw\', \'credit_id\': \'554fa651c3a3681870005275\', \'gender\': 2, \'id\': 114019, \'name\': \'Luke Evans\', \'order\': 19, \'profile_path\': \'/1d31uDYub8TaLOPWfgX78OotduD.jpg\'}, {\'cast_id\': 36, \'character\': \'Safar\', \'credit_id\': \'554fa6d7c3a3685221000283\', \'gender\': 2, \'id\': 492791, \'name\': \'Ali Fazal\', \'order\': 20, \'profile_path\': \'/AmT132VCz3InJBAQQPJnqqgsQsB.jpg\'}, {\'cast_id\': 145, \'character\': \'Jack\', \'credit_id\': \'59a8b72092514157c601fb92\', \'gender\': 0, \'id\': 1880145, \'name\': \'Miller Kimsey\', \'order\': 21, \'profile_path\': None}, {\'cast_id\': 146, \'character\': \'Jack\', \'credit_id\': \'59a8b72b925141579d020797\', \'gender\': 0, \'id\': 1880146, \'name\': \'Charlie Kimsey\', \'order\': 22, \'profile_path\': None}, {\'cast_id\': 133, \'character\': \'Samantha Hobbs\', \'credit_id\': \'56417cfec3a3685be2001846\', \'gender\': 1, \'id\': 1533850, \'name\': \'Eden Estrella\', \'order\': 23, \'profile_path\': \'/xxzcCrgD38jOyCRlbBA5ksfrN14.jpg\'}, {\'cast_id\': 147, \'character\': \'Letty Fan\', \'credit_id\': \'59a8b787c3a36874d5007d12\', \'gender\': 2, \'id\': 1534800, \'name\': \'Gentry White\', \'order\': 24, \'profile_path\': \'/dzu9JUDSHDXrnit7ZlOnJuRJj1X.jpg\'}, {\'cast_id\': 26, \'character\': \'Female Racer\', \'credit_id\': \'5431e01c0e0a265834002c97\', \'gender\': 1, \'id\': 1364893, \'name\': \'Iggy Azalea\', \'order\': 25, \'profile_path\': \'/KG5skDx5WeGDijkUUQnmOP0crG.jpg\'}, {\'cast_id\': 148, \'character\': \'Male Racer\', \'credit_id\': \'59a8b7afc3a3683d0701b1ad\', \'gender\': 0, \'id\': 1161711, \'name\': \'Jon Lee Brody\', \'order\': 26, \'profile_path\': \'/u1agQE1nYgt2LOijksYJMPYxpKh.jpg\'}, {\'cast_id\': 135, \'character\': \'Race Starter\', \'credit_id\': \'56c259c89251414a9b000865\', \'gender\': 1, \'id\': 1578220, \'name\': \'Levy Tran\', \'order\': 27, \'profile_path\': \'/iKcRuLRwmcuoD43E4X0YlYquYGD.jpg\'}, {\'cast_id\': 132, \'character\': \'Hot Teacher\', \'credit_id\': \'56417cc592514128af001862\', \'gender\': 0, \'id\': 118593, \'name\': \'Anna Colwell\', \'order\': 28, \'profile_path\': \'/qerkK7Z26GttfJ8Sq6xMwhkYLq3.jpg\'}, {\'cast_id\': 149, \'character\': \'Doctor\', \'credit_id\': \'59a8b80e92514157ab0206fc\', \'gender\': 0, \'id\': 1880147, \'name\': \'Viktor Hernandez\', \'order\': 29, \'profile_path\': None}, {\'cast_id\': 150, \'character\': \'Priest\', \'credit_id\': \'59a8b84092514157c601fce8\', \'gender\': 2, \'id\': 80619, \'name\': \'Steve Coulter\', \'order\': 30, \'profile_path\': \'/v1cwS9Ia89pO154Wje3m4IxuI3.jpg\'}, {\'cast_id\': 130, \'character\': \'Merc Tech\', \'credit_id\': \'56417c3092514128a6001a15\', \'gender\': 0, \'id\': 97844, \'name\': \'Robert Pralgo\', \'order\': 31, \'profile_path\': \'/iDPgSaDVhwIItvqa2Wn79oaUzf8.jpg\'}, {\'cast_id\': 151, \'character\': \'Weapons Tech\', \'credit_id\': \'59a8b888c3a3683ce601e3aa\', \'gender\': 0, \'id\': 1381712, \'name\': \'Antwan Mills\', \'order\': 32, \'profile_path\': \'/58nvO2Se7TS0ETUEzHHjJ0MLH5U.jpg\'}, {\'cast_id\': 152, \'character\': \'Billionaire\', \'credit_id\': \'59a8b8bac3a36874d5007ea3\', \'gender\': 0, \'id\': 1880148, \'name\': \'J.J. Phillips\', \'order\': 33, \'profile_path\': None}, {\'cast_id\': 153, \'character\': \'Dominican Priest\', \'credit_id\': \'59a8b8ccc3a3683c8701fa73\', \'gender\': 0, \'id\': 1880149, \'name\': \'Jorge Ferragut\', \'order\': 34, \'profile_path\': None}, {\'cast_id\': 154, \'character\': \'Hana\', \'credit_id\': \'59a8b8e3c3a36874d5007ec7\', \'gender\': 0, \'id\': 1440699, \'name\': \'Sara Sohn\', \'order\': 35, \'profile_path\': \'/8nfPK3sFpHzw0uu66LmTK9HcQ5G.jpg\'}, {\'cast_id\': 155, \'character\': \'Merc Driver (as Ben Blankenship)\', \'credit_id\': \'59a8b904c3a3683c7a02381c\', \'gender\': 0, \'id\': 1093707, \'name\': \'Benjamin Blankenship\', \'order\': 36, \'profile_path\': \'/xl0O9d7xS6XGSRqQl16StOxtkOR.jpg\'}, {\'cast_id\': 156, \'character\': \'DJ\', \'credit_id\': \'59a8b953c3a36876710081c2\', \'gender\': 0, \'id\': 1880150, \'name\': \'D.J. Hapa\', \'order\': 37, \'profile_path\': None}, {\'cast_id\': 140, \'character\': \'DJ\', \'credit_id\': \'58eee68c92514142020018f0\', \'gender\': 0, \'id\': 224092, \'name\': \'T-Pain\', \'order\': 38, \'profile_path\': None}, {\'cast_id\': 157, \'character\': \'Drone Tech\', \'credit_id\': \'59a8b98892514157ee01f2d9\', \'gender\': 2, \'id\': 54792, \'name\': \'Brian Mahoney\', \'order\': 39, \'profile_path\': \'/v6pTsqgOHE5TldFV63Kr44idQNe.jpg\'}, {\'cast_id\': 131, \'character\': \'Jasmine\', \'credit_id\': \'56417c7b92514128a90018fb\', \'gender\': 1, \'id\': 1128522, \'name\': \'Brittney Alger\', \'order\': 40, \'profile_path\': \'/u1eKIGLkK2GTpqFArNxgAMTMhOj.jpg\'}, {\'cast_id\': 158, \'character\': \'Mando\', \'credit_id\': \'59a8b9ad92514157ab020902\', \'gender\': 0, \'id\': 1451616, \'name\': \'Romeo Santos\', \'order\': 41, \'profile_path\': \'/lbt98DkUpRNoJXiFbXzQfhMIRt4.jpg\'}, {\'cast_id\': 159, \'character\': \'Advisor\', \'credit_id\': \'59a8b9ca925141579d020ab6\', \'gender\': 1, \'id\': 78804, \'name\': \'Jocelin Donahue\', \'order\': 42, \'profile_path\': \'/eQXBzPjo9K8MG9TVOoQDNoHEFwv.jpg\'}, {\'cast_id\': 160, \'character\': \'Field Reporter\', \'credit_id\': \'59a8b9da9251415808021296\', \'gender\': 0, \'id\': 1880151, \'name\': \'Stephanie Langston\', \'order\': 43, \'profile_path\': None}, {\'cast_id\': 161, \'character\': \'Cop\', \'credit_id\': \'59a8b9f192514157a5020874\', \'gender\': 0, \'id\': 1448173, \'name\': \'Jorge-Luis Pallo\', \'order\': 44, \'profile_path\': \'/9cw97jnvm7SvnCTNBWZHXt4clfu.jpg\'}, {\'cast_id\': 143, \'character\': \'Leo (uncredited / archive)\', \'credit_id\': \'58eee6b8925141423500180f\', \'gender\': 2, \'id\': 96321, \'name\': \'Tego Calder√≥n\', \'order\': 45, \'profile_path\': \'/pz7i7LV35XRC5Si8liRoYWdrcr0.jpg\'}, {\'cast_id\': 142, \'character\': \'Neela (uncredited / archive)\', \'credit_id\': \'58eee6ab92514141ff001971\', \'gender\': 1, \'id\': 116277, \'name\': \'Nathalie Kelley\', \'order\': 46, \'profile_path\': \'/68xBLk7FvQ36v794LbOrMxeOJeQ.jpg\'}, {\'cast_id\': 29, \'character\': \'Twinkie (uncredited)\', \'credit_id\': \'5431e03e0e0a265872002bf2\', \'gender\': 0, \'id\': 58197, \'name\': \'Shad Moss\', \'order\': 47, \'profile_path\': \'/A1rHY9B5R9cIQshClcJxBYINg1m.jpg\'}, {\'cast_id\': 144, \'character\': \'Santos (uncredited / archive)\', \'credit_id\': \'58eee6c492514141f70019b8\', \'gender\': 0, \'id\': 90634, \'name\': \'Don Omar\', \'order\': 48, \'profile_path\': \'/f1INIG2TE9jXXp5A3gGJR9UkePK.jpg\'}, {\'cast_id\': 141, \'character\': \'Race Wars Racer (uncredited)\', \'credit_id\': \'58eee698c3a36826510017dc\', \'gender\': 0, \'id\': 1563213, \'name\': \'Klement Tinaj\', \'order\': 49, \'profile_path\': None}, {\'cast_id\': 139, \'character\': "Brian O\'Conner (uncredited)", \'credit_id\': \'58eee621c3a368265e001729\', \'gender\': 0, \'id\': 1795034, \'name\': \'Caleb Walker\', \'order\': 50, \'profile_path\': None}, {\'cast_id\': 45, \'character\': "Brian O\'Connor (uncredited)", \'credit_id\': \'5589e3fd925141569c00003e\', \'gender\': 2, \'id\': 1480862, \'name\': \'Cody Walker\', \'order\': 51, \'profile_path\': \'/6InC9qPrftOqsRK9ALcKFLHXSLV.jpg\'}]'

In [119]:
import ast
def convert(text):
  if(isinstance(text,str)):
    return ast.literal_eval(text)
  return text
df1['cast']=df1['cast'].apply(convert)
df1['crew']=df1['crew'].apply(convert)

In [120]:
actors_of_high_profit_movie=[]
for i in df1.loc[max_p]['cast']:
  actors_of_high_profit_movie.append(i['name'])

In [121]:
actors_of_high_profit_movie

['Vin Diesel',
 'Paul Walker',
 'Dwayne Johnson',
 'Michelle Rodriguez',
 'Tyrese Gibson',
 'Ludacris',
 'Jordana Brewster',
 'Djimon Hounsou',
 'Tony Jaa',
 'Ronda Rousey',
 'Nathalie Emmanuel',
 'Kurt Russell',
 'Jason Statham',
 'Sung Kang',
 'Gal Gadot',
 'Lucas Black',
 'Elsa Pataky',
 'Noel Gugliemi',
 'John Brotherton',
 'Luke Evans',
 'Ali Fazal',
 'Miller Kimsey',
 'Charlie Kimsey',
 'Eden Estrella',
 'Gentry White',
 'Iggy Azalea',
 'Jon Lee Brody',
 'Levy Tran',
 'Anna Colwell',
 'Viktor Hernandez',
 'Steve Coulter',
 'Robert Pralgo',
 'Antwan Mills',
 'J.J. Phillips',
 'Jorge Ferragut',
 'Sara Sohn',
 'Benjamin Blankenship',
 'D.J. Hapa',
 'T-Pain',
 'Brian Mahoney',
 'Brittney Alger',
 'Romeo Santos',
 'Jocelin Donahue',
 'Stephanie Langston',
 'Jorge-Luis Pallo',
 'Tego Calder√≥n',
 'Nathalie Kelley',
 'Shad Moss',
 'Don Omar',
 'Klement Tinaj',
 'Caleb Walker',
 'Cody Walker']

In [122]:
director = [i['name'] for i in df1.loc[max_p]['crew'] if i['job'] == 'Director']
producer = [i['name'] for i in df1.loc[max_p]['crew'] if i['job'] == 'Producer']

In [123]:
producer

['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']

In [124]:
director

['James Wan']

# question 2: This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [125]:
df2=data.dropna(subset=['spoken_languages']).reset_index(drop=True)

In [126]:
df2=df2[df2['budget']>10000]

In [127]:
profit_data2=pd.DataFrame(df2['revenue']-df2['budget'],columns=['profit'])

In [128]:
df2['ROI']=profit_data2['profit']/df2['budget']

In [129]:
df2['spoken_languages']=df2['spoken_languages'].apply(convert)

In [130]:
df2['language']=df2['spoken_languages'].apply(lambda x:x[0]['name'])

In [131]:
df2['language']

0              English
1              English
2              English
3              English
5              English
             ...
2972       No Language
2973    български език
2977           English
2978           English
2979           English
Name: language, Length: 2159, dtype: object

In [132]:
language_wise=df2.groupby('language')['ROI'].mean()

In [133]:
language_wise.sort_values(ascending=False)   #can check other than No language rows in the output

language
No Language       39.356294
ελληνικά          25.908308
English           13.318084
Türkçe             9.660000
বাংলা              9.043031
Kiswahili          6.590757
עִבְרִית           6.457647
한국어/조선말            5.332218
తెలుగు             4.400768
Polski             4.161383
Deutsch            4.113263
Magyar             4.026290
فارسی              4.000000
广州话 / 廣州話          3.988704
اردو               3.506738
日本語                3.463572
Afrikaans          3.368050
svenska            2.720785
हिन्दी             2.566472
                   2.504137
Español            2.413207
Český              2.404557
普通话                2.398124
Hrvatski           2.288741
Eesti              2.228443
shqip              2.219815
Latin              2.158067
Український        1.882955
தமிழ்              1.591906
العربية            1.543783
Dansk              1.521148
Italiano           1.082594
Français           1.079777
Íslenska           1.067971
ਪੰਜਾਬੀ             1.000000
Català             1.000000
Pусский            0.997381
Esperanto          0.983159
български език     0.859741
Norsk              0.834653
Português          0.743528
Somali             0.438815
Nederlands         0.339617
suomi             -0.031001
Română            -0.496180
Srpski            -0.999604
Name: ROI, dtype: float64

In [134]:
highest_ROI_language=language_wise.idxmax()

In [135]:
highest_ROI_language

'No Language'

#question-3 Find out the unique genres of movies in this dataset.

In [136]:
df3=data.dropna(subset=['genres']).reset_index(drop=True)

In [137]:
df3['genres']=df3['genres'].apply(convert)

In [138]:
df3['genres'][1][0]["name"]

'Comedy'

In [139]:
type(df3['genres'][0])

list

In [140]:
unique_genres=[]

In [141]:
for i in range(len(df3['genres'])):
  for j in range(len(df3['genres'].iloc[i])):
    unique_genres.append(df3['genres'].iloc[i][j]['name'])

In [142]:
set(unique_genres)

{'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Family',
 'Fantasy',
 'Foreign',
 'History',
 'Horror',
 'Music',
 'Mystery',
 'Romance',
 'Science Fiction',
 'TV Movie',
 'Thriller',
 'War',
 'Western'}

#question 4: Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI?

In [143]:
df4=data.dropna(subset=['crew']).reset_index(drop=True)

In [144]:
df4=df4[df4['budget']>10000]

In [145]:
df4['crew']=df4['crew'].apply(convert)

In [146]:
df4['crew'][0]

[{'credit_id': '59ac067c92514107af02c8c8',
  'department': 'Directing',
  'gender': 0,
  'id': 1449071,
  'job': 'First Assistant Director',
  'name': 'Kelly Cantley',
  'profile_path': None},
 {'credit_id': '52fe4ee7c3a36847f82afad7',
  'department': 'Directing',
  'gender': 2,
  'id': 3227,
  'job': 'Director',
  'name': 'Steve Pink',
  'profile_path': '/myHOgo8mQSCiCAZNGMRdHVr03jr.jpg'},
 {'credit_id': '5524ed25c3a3687ded000d88',
  'department': 'Writing',
  'gender': 2,
  'id': 347335,
  'job': 'Writer',
  'name': 'Josh Heald',
  'profile_path': '/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg'},
 {'credit_id': '5524ed2d925141720c001128',
  'department': 'Writing',
  'gender': 2,
  'id': 347335,
  'job': 'Characters',
  'name': 'Josh Heald',
  'profile_path': '/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg'},
 {'credit_id': '5524ed3d92514166c1004a5d',
  'department': 'Production',
  'gender': 2,
  'id': 57822,
  'job': 'Producer',
  'name': 'Andrew Panay',
  'profile_path': None},
 {'credit_id': '5524ed4bc3a3687df3000dd2',
  'department': 'Production',
  'gender': 0,
  'id': 1451395,
  'job': 'Associate Producer',
  'name': 'Adam Blum',
  'profile_path': None},
 {'credit_id': '5524ed5a925141720c00112c',
  'department': 'Production',
  'gender': 2,
  'id': 52997,
  'job': 'Executive Producer',
  'name': 'Rob Corddry',
  'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'},
 {'credit_id': '5524ed85c3a3687e0e000f56',
  'department': 'Production',
  'gender': 0,
  'id': 62807,
  'job': 'Executive Producer',
  'name': 'Ben Ormand',
  'profile_path': None},
 {'credit_id': '5524ed9fc3a3687e0e000f59',
  'department': 'Sound',
  'gender': 2,
  'id': 23486,
  'job': 'Original Music Composer',
  'name': 'Christophe Beck',
  'profile_path': '/2fnJUmCk6IEpVIptpYaUk31epHx.jpg'},
 {'credit_id': '5524eda6c3a3687e03000d28',
  'department': 'Camera',
  'gender': 2,
  'id': 6117,
  'job': 'Director of Photography',
  'name': 'Declan Quinn',
  'profile_path': None},
 {'credit_id': '5524edb4925141720c00113d',
  'department': 'Editing',
  'gender': 0,
  'id': 1451396,
  'job': 'Editor',
  'name': 'Jamie Gross',
  'profile_path': None},
 {'credit_id': '5524edc1925141727600102e',
  'department': 'Production',
  'gender': 0,
  'id': 22219,
  'job': 'Casting',
  'name': 'Susie Farris',
  'profile_path': None},
 {'credit_id': '5524edd192514171cb008257',
  'department': 'Art',
  'gender': 0,
  'id': 1002643,
  'job': 'Production Design',
  'name': 'Ryan Berg',
  'profile_path': None},
 {'credit_id': '555ad9be9251411e5b00d485',
  'department': 'Production',
  'gender': 2,
  'id': 57431,
  'job': 'Executive Producer',
  'name': 'Matt Moore',
  'profile_path': None},
 {'credit_id': '5677e93bc3a36816890087dc',
  'department': 'Directing',
  'gender': 0,
  'id': 1551818,
  'job': 'Script Supervisor',
  'name': 'Nicole Garcea',
  'profile_path': None},
 {'credit_id': '5677e96a92514179e10093d0',
  'department': 'Production',
  'gender': 0,
  'id': 1551819,
  'job': 'Production Coordinator',
  'name': 'Jason Salzman',
  'profile_path': None},
 {'credit_id': '5677e98492514179d2008cd9',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1422996,
  'job': 'Costume Design',
  'name': 'Carol Cutshall',
  'profile_path': None},
 {'credit_id': '5677e9d5c3a368168e009414',
  'department': 'Art',
  'gender': 2,
  'id': 500199,
  'job': 'Set Decoration',
  'name': 'Tim Cohn',
  'profile_path': None},
 {'credit_id': '5677f89d9251417845001a61',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1527917,
  'job': 'Hair Department Head',
  'name': 'Voni Hinkle',
  'profile_path': None},
 {'credit_id': '5677f8b392514179dd0089fb',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1431554,
  'job': 'Makeup Department Head',
  'name': 'Remi Savva',
  'profile_path': None},
 {'credit_id': '5677f8d1c3a3681689008a4b',
  'department': 'Art',
  'gender': 0,
  'id': 66495,
  'job': 'Art Direction',
  'name': 'Jason Baldwin Stewart',
  'profile_path': None},
 {'credit_id': '5677f8eec3a3681685008dd5',
  'department': 'Production',
  'gender': 0,
  'id': 1412466,
  'job': 'Production Supervisor',
  'name': 'Korey Budd',
  'profile_path': None},
 {'credit_id': '5677f90a9251417845001a7d',
  'department': 'Sound',
  'gender': 0,
  'id': 1401562,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Gary C. Bourgeois',
  'profile_path': None},
 {'credit_id': '5677f91e9251417845001a84',
  'department': 'Sound',
  'gender': 0,
  'id': 1396794,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Gabriel J. Serrano',
  'profile_path': None},
 {'credit_id': '5677f938c3a3681680008dd4',
  'department': 'Editing',
  'gender': 0,
  'id': 13168,
  'job': 'Dialogue Editor',
  'name': 'Victoria Rose Sampson',
  'profile_path': None},
 {'credit_id': '5677f94e92514179dd008a1f',
  'department': 'Sound',
  'gender': 0,
  'id': 1551839,
  'job': 'Production Sound Mixer',
  'name': 'Michael B. Koff',
  'profile_path': None},
 {'credit_id': '5677f968c3a368168e009698',
  'department': 'Sound',
  'gender': 0,
  'id': 113052,
  'job': 'Sound Effects Editor',
  'name': 'Randall Guth',
  'profile_path': None},
 {'credit_id': '5677f98dc3a3681685008e02',
  'department': 'Crew',
  'gender': 2,
  'id': 1442535,
  'job': 'Stunt Coordinator',
  'name': 'Chuck Picerni Jr.',
  'profile_path': '/yE5QtXUzcrnCzMRctZL8F5g842B.jpg'},
 {'credit_id': '5677f9a692514179dd008a49',
  'department': 'Camera',
  'gender': 0,
  'id': 1437305,
  'job': 'Camera Operator',
  'name': 'Michael Applebaum',
  'profile_path': None},
 {'credit_id': '5677f9bd9251417845001aae',
  'department': 'Camera',
  'gender': 0,
  'id': 1401765,
  'job': 'Still Photographer',
  'name': 'Steve Dietl',
  'profile_path': None},
 {'credit_id': '5677f9e592514179e7008bf7',
  'department': 'Lighting',
  'gender': 0,
  'id': 1402721,
  'job': 'Rigging Gaffer',
  'name': 'Tarik Naim Alherimi',
  'profile_path': None},
 {'credit_id': '5677f9f4c3a368167c0090ed',
  'department': 'Lighting',
  'gender': 0,
  'id': 1402719,
  'job': 'Gaffer',
  'name': 'Paul Olinde',
  'profile_path': None},
 {'credit_id': '5677fa21c3a368168e0096ca',
  'department': 'Sound',
  'gender': 0,
  'id': 1551840,
  'job': 'Music Supervisor',
  'name': 'Steve Griffen',
  'profile_path': None},
 {'credit_id': '5677fa31c3a3681680008e04',
  'department': 'Sound',
  'gender': 0,
  'id': 1551841,
  'job': 'Music Editor',
  'name': 'Matt Fausak',
  'profile_path': None},
 {'credit_id': '5677fa4392514179dd008a76',
  'department': 'Sound',
  'gender': 0,
  'id': 1551840,
  'job': 'Music Editor',
  'name': 'Steve Griffen',
  'profile_path': None},
 {'credit_id': '5677fa609251417845001acf',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1403416,
  'job': 'Costume Supervisor',
  'name': 'Shonta T. McCray',
  'profile_path': None},
 {'credit_id': '5677fa8492514179d2008fb3',
  'department': 'Camera',
  'gender': 0,
  'id': 1425831,
  'job': 'Steadicam Operator',
  'name': 'Mark Karavite',
  'profile_path': None},
 {'credit_id': '5677fab2c3a3681689008ac3',
  'department': 'Camera',
  'gender': 0,
  'id': 1551842,
  'job': 'First Assistant Camera',
  'name': 'Joe Waistell',
  'profile_path': None},
 {'credit_id': '5677faecc3a368168e0096fe',
  'department': 'Sound',
  'gender': 0,
  'id': 58362,
  'job': 'Supervising Sound Editor',
  'name': 'Michael Hilkene',
  'profile_path': None},
 {'credit_id': '59ac0368c3a3682c0a02c484',
  'department': 'Crew',
  'gender': 0,
  'id': 1881584,
  'job': 'Additional Writing',
  'name': 'John Karnay',
  'profile_path': None},
 {'credit_id': '59ac0411c3a3682bf0028966',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1431552,
  'job': 'Hairstylist',
  'name': 'Daina Daigle',
  'profile_path': None},
 {'credit_id': '59ac0504925141072302b8fb',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1712001,
  'job': 'Makeup Artist',
  'name': 'Allison Gordin',
  'profile_path': None},
 {'credit_id': '59ac0570c3a3682bf0028aac',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 578725,
  'job': 'Makeup Artist',
  'name': 'Darryl Lucas',
  'profile_path': None},
 {'credit_id': '59ac05a4925141077e02c97e',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1463274,
  'job': 'Makeup Artist',
  'name': 'Annabelle MacNeal',
  'profile_path': None},
 {'credit_id': '59ac05c6925141076502d106',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1881586,
  'job': 'Makeup Artist',
  'name': 'Marina Savva',
  'profile_path': None},
 {'credit_id': '59ac0615c3a3682c480296aa',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1406267,
  'job': 'Hairstylist',
  'name': 'Carl G. Variste',
  'profile_path': None},
 {'credit_id': '59ac06ba925141076502d1fa',
  'department': 'Directing',
  'gender': 0,
  'id': 1798593,
  'job': 'First Assistant Director',
  'name': 'Josh King',
  'profile_path': None},
 {'credit_id': '59ac06f1c3a3682c2202aca0',
  'department': 'Art',
  'gender': 0,
  'id': 1415083,
  'job': 'Greensman',
  'name': 'Scott C. Bivona',
  'profile_path': None},
 {'credit_id': '59ac072c925141076502d260',
  'department': 'Art',
  'gender': 0,
  'id': 1881587,
  'job': 'Title Designer',
  'name': 'Eunha Choi',
  'profile_path': None},
 {'credit_id': '59ac077c925141077e02cb62',
  'department': 'Art',
  'gender': 0,
  'id': 1585302,
  'job': 'Construction Coordinator',
  'name': 'Daniel Coe',
  'profile_path': None},
 {'credit_id': '59ac07e0925141078a02d842',
  'department': 'Art',
  'gender': 0,
  'id': 1495523,
  'job': 'Set Designer',
  'name': 'Spencer Davison',
  'profile_path': None},
 {'credit_id': '59ac0862925141072f02cf6f',
  'department': 'Art',
  'gender': 0,
  'id': 1881589,
  'job': 'Painter',
  'name': 'Sonia L. Garcia',
  'profile_path': None},
 {'credit_id': '59ac08e0c3a3682bf0028e51',
  'department': 'Art',
  'gender': 0,
  'id': 1424896,
  'job': 'Art Department Coordinator',
  'name': 'Caleb Guillotte',
  'profile_path': None},
 {'credit_id': '59ac0920c3a3682c2202af36',
  'department': 'Art',
  'gender': 0,
  'id': 1393375,
  'job': 'Leadman',
  'name': "Pat A. O'Connor",
  'profile_path': None},
 {'credit_id': '59ac095592514107af02cc39',
  'department': 'Art',
  'gender': 0,
  'id': 1881592,
  'job': 'Set Designer',
  'name': 'Brendan Turrill',
  'profile_path': None},
 {'credit_id': '59ac0989925141072302bdfa',
  'department': 'Art',
  'gender': 2,
  'id': 76497,
  'job': 'Property Master',
  'name': 'Brook Yeaton',
  'profile_path': None},
 {'credit_id': '59ac0a2cc3a3682c9c02add1',
  'department': 'Sound',
  'gender': 0,
  'id': 1881596,
  'job': 'Boom Operator',
  'name': 'Matthew Armstrong',
  'profile_path': None},
 {'credit_id': '59ac0aa8925141072f02d282',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1558086,
  'job': 'Special Effects Supervisor',
  'name': 'Matt Kutcher',
  'profile_path': None},
 {'credit_id': '59ac0b2ac3a3682c2202b192',
  'department': 'Crew',
  'gender': 2,
  'id': 1558087,
  'job': 'Special Effects Coordinator',
  'name': 'Eric Roberts',
  'profile_path': None},
 {'credit_id': '59ac0b7ac3a3682c2202b1fb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1392098,
  'job': 'Visual Effects Supervisor',
  'name': 'Rocco Passionino',
  'profile_path': None},
 {'credit_id': '59ac0bbe925141077e02d0c4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1558716,
  'job': 'Visual Effects Coordinator',
  'name': 'Joseph Payo',
  'profile_path': None},
 {'credit_id': '59ac0bf2c3a3682cc802cefa',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1408784,
  'job': 'Visual Effects Producer',
  'name': 'Chris Roff',
  'profile_path': None},
 {'credit_id': '59ac0c51c3a3682c48029d99',
  'department': 'Lighting',
  'gender': 0,
  'id': 1881600,
  'job': 'Best Boy Electric',
  'name': 'Ulyan Atamanyuk',
  'profile_path': None},
 {'credit_id': '59ac0cbac3a3682c0a02cff6',
  'department': 'Camera',
  'gender': 0,
  'id': 1881602,
  'job': 'Key Grip',
  'name': 'Chris Ekstrom',
  'profile_path': None},
 {'credit_id': '59ac0d54925141072f02d5e6',
  'department': 'Lighting',
  'gender': 0,
  'id': 1484984,
  'job': 'Best Boy Electric',
  'name': 'Brad Garris',
  'profile_path': None},
 {'credit_id': '59ac0db0925141078a02df86',
  'department': 'Camera',
  'gender': 0,
  'id': 1881603,
  'job': 'Dolly Grip',
  'name': 'Kendell Joseph',
  'profile_path': None},
 {'credit_id': '59ac0e5a925141077e02d39f',
  'department': 'Camera',
  'gender': 0,
  'id': 1549179,
  'job': 'Dolly Grip',
  'name': 'Spencer Wilcox',
  'profile_path': None},
 {'credit_id': '59ac0e9f925141079d02bee6',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1552626,
  'job': 'Key Costumer',
  'name': 'Sarah P. Koeppe',
  'profile_path': None},
 {'credit_id': '59ac0ec1c3a3682bf0029524',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1881605,
  'job': 'Seamstress',
  'name': 'Catherine Rodi',
  'profile_path': None},
 {'credit_id': '59ac0eef925141070702c7ff',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1463801,
  'job': 'Seamstress',
  'name': 'Giselle Spence',
  'profile_path': None},
 {'credit_id': '59ac0f5dc3a3682c4802a0f5',
  'department': 'Production',
  'gender': 0,
  'id': 1400837,
  'job': 'Location Manager',
  'name': 'John A. Johnston',
  'profile_path': None},
 {'credit_id': '59ac0ff2c3a3682c4802a196',
  'department': 'Crew',
  'gender': 0,
  'id': 1844322,
  'job': 'Production Controller',
  'name': 'Gail Marks',
  'profile_path': None}]

In [147]:
producer4=[]
director4=[]

In [148]:
for i in range(len(df4['crew'])):
  l=[]
  for j in range(len(df4['crew'].iloc[i])):
    if(df4['crew'].iloc[i][j]["job"]=="Producer"):
      l.append(df4['crew'].iloc[i][j]["name"])
  producer4.append(l)

In [149]:
for i in range(len(df4['crew'])):
  l=[]
  for j in range(len(df4['crew'].iloc[i])):
    job = df4['crew'].iloc[i][j]["job"]
    if 'director' in job.lower():
      l.append(df4['crew'].iloc[i][j]["name"])
  director4.append(l)

In [150]:
producer4

[['Andrew Panay'],
 ['Whitney Houston', 'Mario Iscovich', 'Debra Martin Chase'],
 ['David Lancaster', 'Michel Litvak', 'Jason Blum', 'Helen Estabrook'],
 ['Sujoy Ghosh'],
 [],
 [],
 ['Karen Murphy'],
 ['Irwin Winkler', 'Robert Chartoff'],
 ['Bruce Cohen', 'Dan Jinks'],
 ['Danny DeVito', 'Michael Shamberg', 'Stacey Sher', 'David Nicksay'],
 ['Jan de Bont', 'Bonnie Curtis', 'Gerald R. Molen', 'Walter F. Parkes'],
 ['Branislav Jeliƒá'],
 ['Chris Bender', 'Marianne Maddalena'],
 [],
 ['Luc Besson', 'Steve Chasman'],
 ['Carla Fry', 'Akiva Goldsman', 'Stephen Hopkins', 'Mark W. Koch'],
 [],
 ['Jean Doumanian'],
 ['David Gross',
  'Macdara Kelleher',
  'Andr√© Rouleau',
  'Jesse Shapira',
  'Marc Stephenson'],
 ['Joe Bacal', 'Tom Griffin'],
 ['Scott Rudin'],
 ['Nicolas Duval-Adassovsky', 'Laurent Zeitoun', 'Yann Zenou'],
 ['Vin Diesel', 'Mark Canton', 'Bernie Goldmann'],
 ['Roger Birnbaum', 'Jonathan Glickman', 'Arthur M. Sarkissian', 'Jay Stern'],
 ['Lawrence Bender', 'Dana Brunetti', 'Joseph Zolfo', 'John R. Woodward'],
 ['Arnold Kopelson', 'Wolfgang Petersen'],
 ['Jerry Bresler'],
 ['Gordon Carroll', 'Carter De Haven Jr.'],
 ['Leslie Dixon', 'Linne Radmin', 'Tom Rosenberg'],
 ['Morgan Freeman',
  'Lori McCreary',
  'Charlie Peters',
  'Curtis Burch',
  'Tracy Mercer'],
 ['Paul Brooks',
  'Jessica Bendinger',
  'Nathalie Marciano',
  'Michelle Chydzik Sowa'],
 [],
 ['Lori Forte'],
 ['Stacey Sher', 'Richard N. Gladstein', 'Shannon McIntosh'],
 ['Rick Berman', 'Peter Lauritson'],
 [],
 ['Martin Jurow'],
 ['Mickey Liddell', 'Patrick Aiello', 'Pete Shilaimon'],
 ['Peter Macgregor-Scott'],
 [],
 ['Barbara Broccoli', 'Michael G. Wilson'],
 ['James Hill'],
 ['Randy Cheveldave', 'Barbara Sachs'],
 ['Albert Berger', 'Ron Yerxa'],
 ['Yoram Globus', 'Menahem Golan', 'Mark DiSalle'],
 [],
 ['Alan J. Pakula', 'Harper Lee', 'Robert Mulligan', 'Gregory Peck'],
 ['Neal H. Moritz'],
 ['George Clooney', 'Steven Soderbergh', 'Peter Guber'],
 ['Rachel Talalay'],
 ['Jeff Begun'],
 ['Michael De Luca', 'Alison R. Rosenzweig'],
 ['A. M. Rathnam'],
 ['Douglas Kenney'],
 ['Rob Zombie',
  'Mike Elliott',
  'Andy Gould',
  'Matthew Perniciaro',
  'Eddie Vaisman',
  'Michael Sherman'],
 ['Sean Daniel', 'James Jacks', 'David Blocker', 'Caldecot Chubb'],
 ['Steve Martin', 'Ashok Amritraj', 'Jon Jashni'],
 ['Iain Softley',
  'Michael Shamberg',
  'Stacey Sher',
  'Daniel Bobker',
  'Lorenzo P. Lampthwait'],
 ['Peter Hyams'],
 ['Laura Lau', 'Agn√®s Mentre'],
 ['Sam Mercer', 'Kathleen Kennedy'],
 ['Stanley R. Jaffe'],
 ['Barbie Tung'],
 ['Jamie Patricof', 'Jeff Abberley', 'Kim Zubick', 'Diane Miller Levin'],
 ['Lawrence Bender', 'Katsuji Morishita'],
 [],
 ['Alain Sarde',
  'Mary Sweeney',
  'Neal Edelstein',
  'Michael Polaire',
  'Tony Krantz'],
 [],
 ['√Ålvaro August√≠n',
  'Ghislain Barrois',
  'Edmon Roch',
  'Jordi Gasull',
  'Ana Jard√≥n Ruiz',
  'Nicolas Matji',
  'Ezequiel Nieto',
  'C√©sar Vargas'],
 ['Robert H. Solo'],
 ['Jeff Young'],
 ['Brian Grazer', 'Ron Howard', 'Maureen Peyrot', 'Kathleen McGill'],
 ['Damian Jones'],
 ['Michael Shamberg', 'Stacey Sher', 'Carla Santos Shamberg'],
 ['Mel Gibson',
  'Bruce Davey',
  'Alan Ladd, Jr.',
  'Dean Lopata',
  'Elisabeth Robinson'],
 [],
 ['Walter Mirisch'],
 ['Barry Levinson',
  'Paula Weinstein',
  'Arnold Rifkin',
  'Ashok Amritraj',
  'Michael Birnbaum',
  'Michele Berk',
  'David Hoberman'],
 ['Elaine Goldsmith-Thomas',
  'William Sherak',
  'Jason Shuman',
  'Deborah Schindler'],
 ['Will Ward', 'Brian Grazer', 'Ron Howard', 'Joe Roth', 'Paula Weinstein'],
 ['Ray Stark'],
 ['Peter Jackson', 'Barrie M. Osborne'],
 ['Brian Grazer', 'Michael Jenkinson', 'Damon Lee'],
 ['Chua Lam', 'Leonard Ho'],
 [],
 ['Bonnie Arnold'],
 ['Alan Greisman', 'Aaron Spelling'],
 [],
 ['Steven J. Wolfe', 'Mason Novick', 'Mark Waters', 'Jessica Tuchinsky'],
 [],
 ['James Jacks',
  'Gary Lucchesi',
  'Tom Rosenberg',
  'Richard S. Wright',
  'Grant Curtis'],
 ['Debra Hill', 'Randi Chernov', 'David Foster', 'Shane Riches'],
 [],
 ['Henry Normal', 'Kevin Loader'],
 [],
 ['Todd Phillips', 'Daniel Goldberg'],
 ['Robert Jones', 'Sarah Curtis'],
 ['Rolf de Heer', 'Julie Ryan'],
 ['Paul Schiff'],
 ['Lauren Shuler Donner', 'Ralph Winter'],
 ['Saul Chaplin'],
 [],
 ['Bret Easton Ellis'],
 ['Mel Ferrer'],
 ['Tae-sung Jeong', 'Steven Nam', 'Park Chan-wook', 'Miky Lee', 'Tae-hun Lee'],
 ['Jeanette Buerling-Milio'],
 ['Jason Blum', 'Elaine Goldsmith-Thomas', 'John Jacobs', 'Jennifer Lopez'],
 [],
 [],
 ['Mark Canton', 'Neil Canton'],
 ['Patrick Markey', 'Allen Shapiro', 'Joshua Donen'],
 [],
 ['Steven Schardt'],
 ['Barry Mendel', 'Paul Schiff'],
 ['Robert Zemeckis', 'Joel Silver', 'Susan Downey', 'Herb Gains'],
 ['Tom Rosenberg',
  'Gary Lucchesi',
  'Beau Flynn',
  'Tripp Vinson',
  'Paul Harris Boardman'],
 ['Blake Edwards'],
 ['Byron Kennedy'],
 ['Elliott Kastner', 'Jerry Gershwin'],
 ['William A. Graham', 'Peter Bogart'],
 [],
 ['Neal H. Moritz'],
 ['Ash R. Shah', 'Daniel Chuba', 'Jamie Dixon'],
 ['Buzz Feitshans'],
 ['Albert R. Broccoli', 'Tom Pevsner', 'Michael G. Wilson'],
 ["Greg O'Connor", 'Robert Hopes', 'Josh Fagin'],
 ['Minami Ichikawa', 'Toichiro Shiraishi'],
 ['Steve Koren',
  "Mark O'Keefe",
  'Neal H. Moritz',
  'Adam Sandler',
  'Jack Giarraputo'],
 [],
 ['Mike Clattenburg'],
 ['Tod Browning', 'Irving Thalberg'],
 ['Jim Morris', 'Lindsey Collins'],
 ['Nancy Rae Stone'],
 ['Mike Medavoy', 'Arnold Messer', 'David Thwaites'],
 [],
 [],
 ['Arnon Milchan', 'Michael Douglas', 'Marcy Drogin'],
 ['Herb Gains',
  'John Gatins',
  'Robert F. Newmyer',
  'Susan E. Novick',
  'Jeffrey Silver',
  'Scott Strauss'],
 ['Peter Chernin', 'Dylan Clark', 'Mike Larocca'],
 ['Jordan Kerner', 'Tony Winley'],
 ['Tony Garnett'],
 [],
 ['Matt Groening',
  'James L. Brooks',
  'Richard Sakai',
  'Al Jean',
  'Mike Scully',
  'Jay Kleckner',
  'Peter Gave',
  'Amanda Moshay',
  'Felicia Nalivansky',
  'Matt Orefice',
  'Claudia Katz'],
 [],
 ['Lucas Akoskin',
  'Terry Botwick',
  'David Oyelowo',
  'Ken Wales',
  'Katrina Wolfe',
  'Alex Garcia'],
 ['Suzanne Todd', 'Haim Saban'],
 ['Casey Silver'],
 [],
 ['David Brown', 'Richard D. Zanuck'],
 ['Ronnie Screwvala', 'Sanjay Leela Bhansali', 'Rajat Rawail'],
 ['Ehud Bleiberg', 'Ariel Vromen'],
 ['Pamela Abdy', 'Scott Stuber', 'Jason Bateman'],
 [],
 ['Ivan Reitman', 'Daniel Goldberg'],
 ['Stacy Peralta', 'Jane Kachmer', 'Agi Orsi'],
 ['Han Sanping', 'John Chong', 'Hong Qin', 'Andy Zhang', 'Li Zhou'],
 ['Gary Gilbert', 'Jordan Horowitz'],
 ['Alan Marshall', 'William S. Beasley', "Louis D'Esposito"],
 ['Michael De Luca', 'Ed Cathell III', 'Ren√© Besson'],
 [],
 ['Phil Feldman', 'Roy N. Sickner'],
 ['Ismail Merchant'],
 ['Hal Lieberman', 'Bill Badalato'],
 [],
 ['Dede Gardner',
  'James Gray',
  'Dale Armin Johnson',
  'Anthony Katagas',
  'Jeremy Kleiner'],
 ['Gilbert Adler'],
 ['Lisa Weinstein', 'Howard W. Koch'],
 ['Wendy Finerman', 'Timothy M. Bourne', 'Jody Gerson'],
 ['Roland Carroll', 'Ryan Carroll', 'Bonne Radford'],
 ['Leslie Morgenstein', 'John Morris', 'Bob Levy'],
 [],
 ['Bernd Eichinger'],
 ['Joel Silver', 'Paul Winze', 'Jonathan D. Krane'],
 ['John Brabourne', 'Richard B. Goodwin'],
 ['A√Øssa Djabri', 'Farid Lahouassa', 'Manuel Munz'],
 ['Joel B. Michaels', 'Laurence Mark', 'Renny Harlin', 'James Gorman'],
 ['Richard Perello'],
 [],
 [],
 ['Baltasar Korm√°kur',
  'Nicky Kentish Barnes',
  'Tim Bevan',
  'Eric Fellner',
  'Evan Hayes',
  'Brian Oliver',
  'Tyler Thompson'],
 ['David Weisbart'],
 [],
 ['Bobby Cohen', 'Douglas Wick'],
 ['Edward R. Pressman', 'Caldecot Chubb'],
 ['Tobey Maguire', 'Jon Kilik', 'Spike Lee', 'Julia Chasman'],
 [],
 ['Kevin Smith', 'Scott Mosier'],
 ['Steve Christian', 'Andreas Grosch', 'Marc Samuelson', 'Peter Samuelson'],
 [],
 ['Judd Apatow', 'Jimmy Miller'],
 ['Michael Grais', 'Steven Seagal', 'Mark Victor'],
 ['John Davis'],
 ['Lauren Shuler Donner', 'Nora Ephron'],
 ['M Shyam Prasad Reddy', 'Bellamkonda Suresh'],
 ['Roger Birnbaum', 'Ivan Reitman'],
 ['Michael Mann', 'Julie Richardson'],
 ['Joss Whedon'],
 ['Danny DeVito', 'Michael Shamberg', 'Stacey Sher'],
 ['Bruno Levy'],
 ['David Ayer', 'Matt Jackson', 'John Lesher'],
 ['Stuart Gordon',
  'Peter Newman',
  'Ted Mann',
  'Mary Breen-Farrelly',
  'Greg Johnson'],
 ['Mark Bienstock', 'Jason Blum', 'M. Night Shyamalan'],
 ['Stephanie Allain', 'Gina Prince-Bythewood', 'Erwin Stoff'],
 [],
 ['Duncan Kenworthy'],
 ['Walter F. Parkes',
  'Roger Birnbaum',
  'Gary Barber',
  'Laurence Mark',
  'Ivan Oyco'],
 ['Clayton Townsend', 'Erwin Stoff', 'Angelina Jolie', 'Matthew Barr'],
 ['Jon Kilik', 'Nina Jacobson'],
 ['Tom Shadyac',
  'Roger Birnbaum',
  'Gary Barber',
  'Mark Johnson',
  'Alan B. Curtiss',
  'Janet L. Wattles',
  'Arlene Kehela'],
 ['Joel Silver'],
 ['Paul Mazursky'],
 ['John Byers', 'Mary Ann Page'],
 ['Brent Maddock', 'S. S. Wilson'],
 [],
 ['Gerry Robert Byrne',
  'Harvey Weinstein',
  'Alberto Grimaldi',
  'Joseph P. Reidy',
  'Laura Fattori'],
 ['Tom Hanks',
  'Vincent Landay',
  'Gary Goetzman',
  'John B. Carls',
  'Maurice Sendak'],
 ['Ben Affleck', 'Leonardo DiCaprio', 'Jennifer Killoran', 'Jennifer Todd'],
 ['Roger Birnbaum', 'Gary Barber', 'Maggie Wilde'],
 ['Andrew Gunn'],
 ['Ivan Reitman',
  'Simone Urdl',
  'Jennifer Weiss',
  'Joe Medjuck',
  'Erin Cressida Wilson',
  'Jeffrey Clifford',
  'Ali Bell'],
 [],
 ['Shakim Compere', 'Otis Best'],
 ['Kevin Reher'],
 ['Clint Eastwood', 'Brian Grazer', 'Robert Lorenz', 'Ron Howard'],
 [],
 ['Simon Kinberg', 'Bill Block', 'Neill Blomkamp'],
 [],
 ['Edward S. Feldman'],
 ['Brett Ratner',
  'Ryan Kavanaugh',
  'Bernie Goldmann',
  'Ken Halsband',
  'Nico Soultanakis',
  'Andy Berman',
  'Ajit Singh'],
 ['Steve Golin',
  'Arnon Milchan',
  'James W. Skotchdopole',
  'David Kanter',
  'Keith Redmon',
  'Mary Parent'],
 ['Bruce Davey'],
 [],
 ['John Davis', 'David T. Friendly'],
 ['Scott Rudin'],
 ['Luc Besson', 'Pierre-Ange Le Pogam', 'Gareth Upton'],
 ['Tobey Maguire', 'Jenno Topping', 'George Flynn', 'Meredith Zamsky'],
 ['George Miller', 'Doug Mitchell', 'Bill Miller'],
 [],
 ['Fisher Stevens', 'John Penotti', 'Matthew H. Rowland'],
 [],
 ['Bobby Cohen', 'Alex Kurtzman', 'Roberto Orci'],
 ['Mark Huffam', 'Mike Jefferies', 'Matt Barrelle'],
 ['Walter Bernstein', 'Martin Ritt'],
 ['David Brown', 'Joe Wizan', 'Steve Wizan'],
 ['Lorenzo di Bonaventura',
  'Alexander Dostal',
  'Mace Neufeld',
  'David Ready',
  'David Barron',
  'Mark Vahradian'],
 ['Anthony Bregman',
  'Allan Loeb',
  'Michael Sugar',
  'Kevin Scott Frakes',
  'Brad Dorros'],
 ['Isao Takahata'],
 [],
 ['Lorenzo di Bonaventura', 'Mark Wahlberg', 'Mark Vahradian', 'David Womark'],
 ['Albert R. Broccoli', 'Harry Saltzman', 'Stanley Sopel'],
 [],
 ['Gale Anne Hurd'],
 ['Stephanie Austin', 'Mace Neufeld', 'Howard Baldwin', 'Karen Elise Baldwin'],
 [],
 ['Jerry Weintraub', 'James G. Robinson'],
 ['Peter Jackson',
  'Fran Walsh',
  'Philippa Boyens',
  'Carolynne Cunningham',
  'Aim√©e Peyronnet',
  'Marc Ashton',
  'Anne Bruning'],
 [],
 [],
 ['Jacques Audiard',
  'Pascal Caucheteux',
  'Martine Cassinelli',
  'Alix Raynaud'],
 ['Pieter Jan Brugge', 'Michael Mann'],
 ['T.D. Jakes', 'Joe Roth'],
 ['Jason Blum', 'Matthew Kaplan', 'Jimmy Miller', 'Cody Zwieg'],
 ['Ronnie Screwvala', 'Manish Hariprasad', 'Siddharth Roy Kapur'],
 ['John Davis'],
 ['Robert F. Colesberry', 'Griffin Dunne', 'Amy Robinson'],
 ['Igo Kantor', 'Jeffrey M. Sneller'],
 ['Richard A. Roth'],
 [],
 ['Joel Coen', 'Ethan Coen'],
 [],
 ['Edward Zwick',
  'Marshall Herskovitz',
  'Gillian Gorfil',
  'Graham King',
  'Darrell James Roodt',
  'Paula Weinstein',
  'Genevieve Hofmeyr',
  'Josh Gummersall',
  'Philip Key'],
 ['Jean-Jacques Annaud', 'Jake Eberts'],
 ['Steve Golin', 'Sigurj√≥n Sighvatsson'],
 ['Clayton Townsend', 'Dan Halsted', 'Lauren Shuler Donner'],
 ['Tim Bevan', 'Eric Fellner', 'Peter Bennett-Jones'],
 ['Saul Zaentz'],
 ['George Furla', 'Randall Emmett', '50 Cent'],
 ['Barry Bernardi', 'Jack Giarraputo'],
 [],
 ['Timur Bekmambetov'],
 ['Chris Columbus', 'Mark Radcliffe', 'Michael Barnathan', 'Richard Vane'],
 ['Albert S. Ruddy'],
 ['Hunt Lowry', 'Michael Mann'],
 ['John Fiedler'],
 ['Jennifer Todd', 'Suzanne Todd', 'Gary David Goldberg'],
 [],
 ['Stokely Chaffin', 'Erik Feig', 'Neal H. Moritz'],
 ['Frank Mancuso Jr.'],
 ['Clayton Townsend', 'Dan Halsted'],
 ['Scott Kroopf', 'Michael S. Murphey', 'Joel Soisson'],
 ['Gale Anne Hurd'],
 ['Gary Ross', 'Frank Marshall', 'Jane Sindell'],
 ['Wyck Godfrey', 'Marty Bowen', 'Ryan Kavanaugh'],
 [],
 ['Scott Rudin', 'Sacha Baron Cohen', 'Anthony Hines'],
 ['Mace Neufeld'],
 ['Michael London', 'Jeffrey Kusama-Hinte'],
 [],
 ['Letty Aronson', 'Stephen Tenenbaum', 'Jaume Roures'],
 ['Michael Grais', 'Mark Victor'],
 ['Jenny Wiener Steingart', 'Jon Steingart'],
 ['Aaron Ryder', 'Marc D. Evans', 'Trevor Macy'],
 [],
 [],
 ['Hal McElroy', 'Jim McElroy'],
 ['Christopher Nolan', 'Aaron Ryder', 'Emma Thomas'],
 ['Richard Linklater', 'Ginger Sledge', 'Megan Ellison'],
 ['Chris Bender', 'A.J. Dix', 'J.C. Spink', 'Anthony Rhulen'],
 [],
 ['John Baldecchi', 'Lawrence Bender'],
 ['Paula Weinstein',
  'Mark Polish',
  'Michael Polish',
  'Len Amato',
  'Robert Benjamin',
  'Jonathan Sheldon'],
 ['Tim Bevan', 'Eric Fellner', 'Mark Huffam'],
 ['Mark Burg', 'Thom Mount', 'Charles Hirschhorn'],
 ['Sa√Ød Ben Sa√Ød', 'Emilie Lesclaux', 'Michel Merkt'],
 ['Gianni Nunnari',
  'Zack Snyder',
  'Mark Canton',
  'Thomas Tull',
  'Bernie Goldmann',
  'Deborah Snyder'],
 ['Alain Attal'],
 ['Craig Baumgarten', 'Peter Hyams', 'Moshe Diamant'],
 ['George Miller', 'Doug Mitchell', 'Bill Miller'],
 ['Wolfgang Petersen', 'Gail Katz', 'Armyan Bernstein', 'Jonathan Shestack'],
 ['Frank H√ºbner',
  'Andrew Stevens',
  'Jan Fantl',
  'Howard Baldwin',
  'Karen Elise Baldwin',
  'Moshe Diamant',
  'Steven Cantor'],
 ['David Parfitt', 'Broderick Johnson', 'Andrew A. Kosove'],
 ['Lawrence Mortorff'],
 ['David O. Selznick'],
 [],
 ['Tom Hanks', 'Rita Wilson'],
 ['Robert Rodriguez', 'Bill Borden'],
 ['Mark Ciardi', 'Gordon Gray'],
 ['Steve Starkey', 'Robert Zemeckis'],
 [],
 ['Robert Chartoff', 'Irwin Winkler'],
 ['James G. Robinson',
  'Dara Resnik Creasey',
  'Clifford Werber',
  'David C. Robinson'],
 ['Andrew Mason', 'Philippe Carcassonne', 'Barbara Gibbs', 'Michel Feller'],
 ['David Siegel', 'Todd Phillips', 'Daniel Goldberg', 'Jeffrey Wetzel'],
 ['Leonard Goldberg'],
 [],
 [],
 [],
 [],
 ['Joel Simon', 'Jonathan Winfrey'],
 ['Ramesh Sippy', 'Mukesh Talreja', 'Rohan Sippy'],
 ['Julie Ansell'],
 [],
 ['Bill Holderman'],
 ['Patrick Markey', 'Robert Redford', 'Joseph P. Reidy', 'Karen Tenkhoff'],
 [],
 ['Michael Bay',
  'Jason Blum',
  'Andrew Form',
  'Bradley Fuller',
  'Sebastien Lemercier'],
 [],
 ['Melanie Coombs'],
 ['Robert Redford',
  'Tracy Falco',
  'Matthew Michael Carnahan',
  'Andrew Hauptman'],
 ['Gary Levinsohn', 'Ben Cosgrove', 'Todd Wagner', 'Shelly Clippard'],
 [],
 [],
 ['Wes Ball',
  'Mark Canton',
  'T.S. Nowlin',
  'Ridley Scott',
  'Courtney Solomon'],
 ['Dylan Sellers', 'Dan Paulson', 'Lee Rich'],
 ['Robert Smigel'],
 [],
 [],
 ['Thierry Marro', 'Benoit Ponsaill√©'],
 ['Robert De Niro',
  'Art Linson',
  'Jane Rosenthal',
  'Barry Levinson',
  'Mark Allan',
  'Mark Cuban',
  'Todd Wagner',
  'Eric Kopeloff'],
 ['Arnold Kopelson', 'Anne Kopelson'],
 ['Eric Watson'],
 ['Mark Canton', 'Alexandre Aja', 'Scott C. Silver', 'Chady Eli Mattar'],
 ['Sam Spiegel'],
 ['Gavin Polone'],
 ['Moshe Diamant', 'Sam Raimi'],
 ['Judy Hofflund', 'Gavin Polone'],
 ['G. Srinivasan'],
 ['Eric Fellner', 'Lisa Bruce', 'Anthony McCarten', 'Tim Bevan'],
 ['Paul Thomas Anderson', 'Daniel Lupi', 'JoAnne Sellar', 'Megan Ellison'],
 ['Keith Addis', 'David Nicksay', 'Nick Wechsler'],
 ['Tim Burton', 'Lynette Howell', 'Scott Alexander', 'Larry Karaszewski'],
 ['Cecil B. DeMille'],
 ['Michael Loveday'],
 ['Arnon Milchan', 'Denise Di Novi', 'Nicole Kidman', 'Alison Greenspan'],
 ['Michael De Luca', 'Mike Myers'],
 ['Jennifer Fox', 'Laura Bickford', 'Kerry Orent'],
 ['Arnon Milchan',
  'Donald Petrie',
  'Arnold Rifkin',
  'Ellen H. Schwartz',
  'Marjorie Shik'],
 ['Frank Ross'],
 [],
 ['Robert Rodriguez', 'John Davis', 'Elizabeth Avellan'],
 ['Jay Sanders'],
 ['Spike Lee', 'Luigi Musini', 'Roberto Cicutto'],
 ['Loretha C. Jones', 'David Gale'],
 ['Jerry Bruckheimer', 'Don Simpson'],
 ['Robert Watts', 'Arthur F. Repola'],
 ['Greg Berlanti', 'Sarah Schechter', 'Paul Webster'],
 ['Richard Linklater', 'Sean Daniel', 'James Jacks'],
 ['William S. Beasley', 'Stokely Chaffin', 'Erik Feig', 'Neal H. Moritz'],
 ['Barrie M. Osborne', 'Peter Jackson'],
 ['Robert Arthur'],
 ['Frank Mancuso Jr.', 'Aaron Mazzolini', "Lorenzo O'Brien"],
 ['Michael Besman', 'Harry Gittes'],
 ['Richard P. Rubinstein', 'Mitchell Galin'],
 [],
 ['David Zucker'],
 ['Simon Kinberg', 'Neill Blomkamp'],
 ['Susan Downey', 'Joel Silver', 'Robert Zemeckis', 'L. Levin'],
 ['Haruyo Kanesaku', 'Yutaka Maseba'],
 ['Steven J. Wolfe', 'David E. Talbert', 'Lyn Talbert'],
 ['Matthew Vaughn',
  'Adam Bohling',
  'Valerie Van Galder',
  'David Reid',
  'Rupert Maconick'],
 ['Fred Roos', 'Tom Sternberg'],
 ['Steve Golin', 'Nancy Juvonen', 'Jack Giarraputo'],
 ['Stacey Sher', 'Erwin Stoff', 'John Wells'],
 ['John Wayne', 'James Edward Grant', 'Michael Wayne'],
 ['Wendy Finerman', 'Tom Rosenberg', 'Gary Lucchesi', 'Sidney Kimmel'],
 ['Denise Di Novi', 'Alison Greenspan', 'Ravi D. Mehta'],
 ['Marshall Brickman', 'Jennifer Ogden'],
 ['Andrew Macdonald'],
 ['Andy Gould'],
 ['Graham King', 'Tim Headington', 'Michael Wearing'],
 ['Brad Zions', 'Eden Wurmfeld'],
 [],
 ['Robert Tapert'],
 ['Bobby Cohen', 'Clayton Townsend'],
 ['John Sloss', 'Christine Vachon', 'James D. Stern', 'John Goldwyn'],
 ['Gianni Nunnari', 'Meir Teper'],
 ['Aamir Khan', 'Siddharth Roy Kapur', 'Kiran Rao'],
 [],
 ['Paul W.S. Anderson', 'Jeremy Bolt', 'Robert Kulzer', 'Samuel Hadida'],
 ['William Castle'],
 ['Barbara De Fina'],
 ['Darren Aronofsky', 'Scott Franklin'],
 ['Christos V. Konstantakopoulos', 'Richard Linklater', 'Sara Woodhatch'],
 ['Richard P. Rubinstein'],
 ['Peter Saraf',
  'Marc Turtletaub',
  'Albert Berger',
  'David T. Friendly',
  'Ron Yerxa'],
 ['Anne Walker-McBay', 'Christine Vachon', 'Jocelyn Hayes'],
 ['Jonathan King',
  'Guy East',
  'Nigel Sinclair',
  'Dwayne Johnson',
  'Dany Garcia',
  'Matt Jackson',
  'Alexander Yves Brunner',
  'David Fanning'],
 ['Jerry Bruckheimer', 'Don Simpson'],
 ['Tommy Oliver', 'Darryl Taja', 'Wendy Rhoads', 'Nicole Rocklin'],
 ['Brian Helgeland', 'Tim Van Rellim', 'Todd Black'],
 ['Andrew Lazar'],
 ['Robert Daley'],
 ['D.W. Griffith'],
 ['Sarah Timmins'],
 ['Jonathan A. Zimbert'],
 ['Syd Lim', 'Park Chan-wook'],
 ['Julio Fern√°ndez'],
 [],
 ['Carl Foreman'],
 ['John Hughes', 'Richard Vane'],
 ['Art Linson', 'Irving Azoff'],
 ['Leonard Goldberg'],
 ['Celia Duval', 'Gary Foster', 'Russ Krasnoff'],
 ['John McTiernan', 'Stephen J. Roth'],
 ['Barry Bernardi', "Carr D'Angelo", 'Todd Garner'],
 ['Sam Zimbalist', 'William Wyler'],
 ['Aditya Chopra'],
 ['Emma Tillinger Koskoff',
  'Ben Younger',
  'Pamela Thur',
  'Noah Kraft',
  'Chad A. Verdi',
  'Bruce Cohen'],
 ['Michael London', 'George Parra'],
 ['Billy Wilder', 'I. A. L. Diamond'],
 ['Paul Michael Glaser', 'Jean-Claude Van Damme', 'Ashok Amritraj'],
 ['Bernd Eichinger', 'Ralph Winter', 'Avi Arad'],
 ['Bernd Eichinger', 'Dieter Geissler', 'Bernd Schaefers'],
 ['Patrick Wachsberger', 'Erik Feig', 'Adam Shankman', 'Jennifer Gibgot'],
 [],
 ['Norman Jewison', 'Armyan Bernstein', 'John Ketcham'],
 ['Guillermo del Toro', 'Brad Booker'],
 ['George Folsey Jr.', 'Robert D. Wachs'],
 [],
 ['Liz Watts'],
 ['Jennifer Fox', 'Georgia Kacandes', 'Michael Nozik'],
 ['Dino De Laurentiis'],
 ['Nick Park',
  'Peter Lord',
  'David Sproxton',
  'Carla Shelley',
  'Claire Jennings'],
 ['Lindsay Doran'],
 ['Yoram Ben-Ami', 'Steve Carver'],
 [],
 ['Esteban Ibarretxe', 'Eduardo Carneros', 'Javier Ibarretxe'],
 ['Francis Ford Coppola', 'Fred Fuchs', 'Patrick J. Palmer'],
 ['Danny DeVito', 'Michael Shamberg'],
 ['Olivier Delbosc',

In [151]:
director4

[['Kelly Cantley', 'Steve Pink', 'Declan Quinn', 'Josh King'],
 ['Garry Marshall', 'Charles Minsky'],
 ['Sharone Meir', 'Damien Chazelle', 'Nicolas Duchemin Harvard'],
 ['Sujoy Ghosh'],
 ['Hal Sutherland'],
 ['Ole Bornedal', 'Dan Laustsen', 'Randy Hutniak'],
 ['Christopher Guest', 'Arlene Nelson'],
 ['Steve Perry', 'Fred T. Gallo', 'James Crabe', 'John G. Avildsen'],
 ['Sam Mendes',
  'Conrad L. Hall',
  'Catherine Smith',
  'Tony Adler',
  'Rosemary C. Cremona'],
 ['Jeffrey L. Kimball', 'F. Gary Gray'],
 ['Steven Spielberg',
  'Janusz Kami≈Ñski',
  'Chris Gorak',
  'Jeffrey Mossa',
  'Pete Romano',
  'Sergio Mimica-Gezzan',
  'David H. Venghaus Jr.'],
 ['Stevan Filipoviƒá', 'Mihajlo Savic'],
 ['Wes Craven', 'Robert D. Yeoman'],
 ['Phil Traill'],
 ['Louis Leterrier', 'Mitchell Amundsen', 'Mehdi Sayah', 'Fabrice Bismuth'],
 ['Stephen Hopkins',
  'Peter Levy',
  'Keith Pain',
  'Chris Carreras',
  'Cliff Lanning',
  'Robert Grayson'],
 ['Steve Miner', 'Steve Miner', 'Gerald Feil'],
 ['David Mamet', 'Gabriel Beristain'],
 ['Michael Dowse', 'Rogier Stoffers'],
 ['Nelson Shin', 'Masatoshi Fukui'],
 ['Roger Michell', 'Salvatore Totino'],
 ['Mathieu Vadepied',
  'Eric Toledano',
  'Olivier Nakache',
  'Gabriel Botcherby',
  'Ma√´lys Deschard',
  'Charles Rempenault'],
 ['Dean Semler', 'Breck Eisner'],
 ['James Muro', 'Brett Ratner'],
 ['Stefan Czapsky', 'Boaz Yakin'],
 ['Wolfgang Petersen', 'Michael Ballhaus'],
 ['Sam Leavitt', 'Sam Peckinpah'],
 ['Conrad L. Hall', 'Hank Moonjean', 'Stuart Rosenberg'],
 ['John Schlesinger', 'Elliot Davis'],
 ['Richard Loncraine', 'Jonathan Freeman'],
 ['Clare Kilner'],
 ['Giuseppe Capotondi', 'Tat Radcliffe'],
 ['Carlos Saldanha'],
 ['Quentin Tarantino', 'Robert Richardson', 'Kil Won Yu'],
 ['David Carson', 'John A. Alonzo'],
 ['Christophe Van Rompaey'],
 ['Blake Edwards', 'Russell Harlan'],
 ['Kevin Reynolds', 'Lorenzo Senatore'],
 ['Joel Schumacher',
  'Stephen Goldblatt',
  'William M. Elvin',
  'Richard Holland',
  'Charlie Daboub'],
 ['Kevin Bray'],
 ['Martin Campbell',
  'Phil Meheux',
  'Bruce Moriarty',
  'Simon Lamont',
  'Peter Dorme',
  'Guy Bradley',
  'Molly Sole',
  'Consuelo Bidorini',
  'Lorenzo Marangoni',
  'Lisa Romano',
  'Jakub Dvorak'],
 ['Robert Krasker', 'Carol Reed'],
 ['Rob Hedden', 'Bryan England'],
 ['Alexander Payne', 'Phedon Papamichael', 'George Parra'],
 ['Newt Arnold', 'David Worth'],
 ['Paul Cameron', 'Malcolm Venville'],
 ['Robert Mulligan', 'Russell Harlan', 'Joseph E. Kenney', 'Terry Morse, Jr.'],
 ['Justin Lin', 'Stephen F. Windon'],
 ['Peter Deming', 'John Maybury'],
 ['John Waters', 'David Insley'],
 ['Michael Miller', 'Bruce Logan'],
 ['Craig Gillespie'],
 ['Rajiv Menon'],
 ['Harold Ramis', 'Stevan Larner'],
 ['Rob Zombie', 'David Daniel'],
 ['Ron Shelton', 'Barry Peterson'],
 ['Peter Suschitzky', 'Anand Tucker'],
 ['Iain Softley',
  'Daniel Mindel',
  'Jann Engel',
  'Phil Pastuhov',
  'Gary Marcus'],
 ['Peter Hyams', 'Peter Hyams'],
 ['Chris Kentis', 'Laura Lau'],
 ['Frank Marshall', 'Allen Daviau'],
 ['Robert Benton',
  'N√©stor Almendros',
  'Thomas John Kane',
  'Ira Halberstadt',
  'Lewis Gould'],
 ['Stanley Tong'],
 ['Niki Caro', 'Andrij Parekh'],
 ['Quentin Tarantino',
  'Robert Richardson',
  'Katsuhito Ishii',
  'Satoko Saito',
  'Kennedy Taylor',
  'Jonathan Tex Levitt',
  'Texas Dave'],
 ['Thierry Arbogast', 'Jean-Paul Rappeneau'],
 ['David Lynch', 'Peter Deming'],
 ['Tom Stern', 'Fr√©d√©ric Jardin'],
 ['Enrique Gato'],
 ['Dennis Hopper', 'Haskell Wexler'],
 ['Mark Irwin', 'Craig R. Baxley'],
 ['Ron Howard', 'Roger Deakins', 'Bradley Mayer', 'Nancy Winters'],
 ['Ben Smithard', 'Luke Hull', 'Amma Asante', 'Ben Smith'],
 ['Andrew Dunn', 'Tom Vaughan'],
 ['Mel Gibson',
  'John Toll',
  'Daniel T. Dorrance',
  'Clare Langan',
  "Padraig O'Neill",
  'Anna Rackard',
  'Brendan Rankin'],
 ['Oliver Parker'],
 ['Russell Harlan', 'George Roy Hill'],
 ['Barry Levinson', 'Josh McLaglen', 'Dante Spinotti', 'Kurt E. Soderling'],
 ['Theo van de Sande', 'Nick Hurran'],
 ['Ron Howard',
  'Anthony Dod Mantle',
  'James Collins',
  'Isabel G√≥mez-Blanco',
  'Christian Huband',
  'Niall Moroney'],
 ['Mike Nichols', 'Bill Butler'],
 ['Peter Jackson', 'Andrew Lesnie'],
 ['Malcolm D. Lee', 'Tom Priestley Jr.'],
 ['Sammo Hung', 'Raymond Lam'],
 ['Matthew F. Leonetti', 'Brett Ratner'],
 ['Kevin Lima', 'Chris Buck'],
 ['Colin D. Irwin', 'Bob Clark', 'Reginald H. Morris'],
 ['Andrzej Bartkowiak', 'Glen MacPherson'],
 ['Eric Steelberg', 'Marc Webb'],
 ['Roger Spottiswoode', 'Zhao Xiaoding'],
 ['Sam Raimi', 'Jamie Anderson', 'C. Scott Baker'],
 ['Rupert Wainwright', 'Nathan Hope'],
 ['Spike Lee'],
 ['Declan Lowney', 'Ben Smithard'],
 ['Lance Daly'],
 ['Shepherd Frankel', 'Lawrence Sher', 'Todd Phillips'],
 ['David Schwimmer'],
 ['Ian Jones', 'Rolf de Heer', 'Peter Djigirr'],
 ['Hart Bochner',
  'Reynaldo Villalobos',
  'Martin Walters',
  'Walter Gasparovic'],
 ['Bryan Singer', 'Newton Thomas Sigel', 'Geoff Hubbard'],
 ['Robert Wise', 'Ernest Laszlo'],
 ['Bryan Buckley', 'Scott Henriksen'],
 ['Gregor Jordan'],
 ['Terence Young', 'Charles Lang', 'Jack Aldworth'],
 ['Bong Joon-ho', 'Kyung-Pyo Hong', 'Jakub Dvorak'],
 ['John Stockwell',
  'Florian Friedmann',
  'Tom Hannam',
  'Jean-Fran√ßois Hensgens'],
 ['Rob Cohen', 'David McFarland'],
 ['Robin Budd', 'Donovan Cook'],
 ['Aleksei Sidorov'],
 ['Stephen T. Kay', 'Mauro Fiore', 'Kevin Fair'],
 ['Sam Raimi', 'Dante Spinotti'],
 ['Adam Rapp'],
 ['Lynn Shelton', 'Benjamin Kasulke'],
 ['Wes Anderson', 'Robert D. Yeoman'],
 ['Stephen Hopkins', 'Peter Levy'],
 ['Tom Stern', 'Scott Derrickson', 'Kendelle Elliott'],
 ['Blake Edwards', 'Geoffrey Unsworth', 'Bert Batt', 'Guy Sauteret'],
 ['Dean Semler', 'George Miller'],
 ['Conrad L. Hall', 'James H. Brown', 'Jack Smight'],
 ['Robert Steadman', 'William A. Graham'],
 ['Stephan Elliott'],
 ['Rob Cohen',
  'Ericson Core',
  'Lars P. Winther',
  'Rebecca Marie',
  'Michael Stone'],
 ['Walter Hill', 'Lloyd Ahern II', 'Scott Meehan', 'Jack Sholder'],
 ['Ted Kotcheff',
  'Andrew Laszlo',
  'Craig Huston',
  'Otta Hanus',
  'Jacques Hubert'],
 ['John Glen', 'Alec Mills'],
 ['Declan Quinn', "Gavin O'Connor"],
 ['Takashi Miike'],
 ['Dean Semler', 'Frank Coraci'],
 ['Richard A. Colla'],
 ['Mike Clattenburg'],
 ['Tod Browning', 'Percy Hilburn'],
 ['Andrew Stanton', 'Jeremy Lasky'],
 ['Gerry Lively', 'Kevin Yagher', 'Joe Chappelle'],
 ['Xavier Grobet', 'Kirk Jones'],
 ['Edward Lachman', 'Todd Solondz'],
 ['Armand Mastroianni'],
 ['Gabriel Beristain', 'Clark Johnson'],
 ['Brian Robbins'],
 ['Micha√´l R. Roskam', 'Nicolas Karakatsanis', 'Dan-ah Kim', 'Ryan Palmer'],
 ['Seamus McGarvey', 'Gary Winick'],
 ['Oliver Stapleton', 'Julien Temple'],
 ['Jimmy Hayward'],
 ['David Silverman', 'Gary McCarver', 'Matthew Schofield'],
 ['Howard Storm'],
 ['Jerry Jameson', 'Luis David Sansans'],
 ['Paul Murphy', 'Bryan Spicer'],
 ['Joe Johnston',
  'Shelly Johnson',
  'Troy Sizemore',
  'William M. Elvin',
  'Patricio M. Farrell',
  'Hans Bjerno',
  'Yann Mari Faget',
  'Tarik Ait Ben Ali',
  'Jae Cheol Hong'],
 ['Egon Werdin', 'Anthony Waller'],
 ['Steven Spielberg',
  'Bill Butler',
  'Barbara Bass',
  'Tom Joyner',
  'L. Andrew Stone'],
 ['Prabhu Deva', 'Santosh Thundiiayil'],
 ['Ariel Vromen', 'Bobby Bukowski'],
 ['Javier Aguirresarobe', 'Seth Gordon'],
 ['Takashi Yamazaki', 'Ry≈´ichi Yagi'],
 ['Ivan Reitman', 'Bill Butler'],
 ['Stacy Peralta', 'Peter Pilafian'],
 ['Lu Chuan', 'Yu Cao'],
 ['Masanobu Takayanagi', 'Keith Bearden'],
 ['Jan de Bont', 'Paul Verhoeven'],
 ['Patrick Lussier', 'Brian Pearson', 'Simeon Asenov'],
 ['Lone Scherfig', 'John de Borman'],
 ['Sam Peckinpah', 'Lucien Ballard', 'Clifford C. Coleman'],
 ['James Ivory'],
 ['Phil Meheux',
  'Sarah Horton',
  'Frank Coraci',
  'Gary Freeman',
  'Adam Dale',
  'Nick Heckstall-Smith',
  'George Walker',
  'Paul Goldsmith'],
 ['Victor Nunez', 'Alex Vlacos', 'Jennifer Fong'],
 ['James Gray', 'Darius Khondji', 'Adam Dale'],
 ['Gilbert Adler', 'Tom Priestley Jr.'],
 ['Adam Greenberg', 'Jerry Zucker', 'Doug Chiang'],
 ['Charles Stone III'],
 ['Dan St. Pierre', 'Dougg Williams'],
 ['Tim Orr', 'Sean Anders'],
 ['Chuck Russell', 'John R. Leonetti'],
 ['Rainer Klausmann',
  'Oliver Hirschbiegel',
  'Bohdan Graczyk',
  'Aleksey Filatov',
  'Sergey Fukalov',
  'Hanus Polak Jr.'],
 ['Dominic Sena', 'Paul Cameron'],
 ['Jack Cardiff', 'John Guillermin'],
 ['Thomas Gilou'],
 ['Peter Levy', 'Renny Harlin'],
 ['Lawrence Sher',
  'Jay Chandrasekhar',
  'Fernando Altschul',
  'Francisco Ramirez',
  'Brett Hool'],
 ['Jun Lana', 'Carlo Mendoza'],
 ['Jason Bateman'],
 ['Baltasar Korm√°kur',
  'Salvatore Totino',
  'Tom Still',
  'Gianpaolo Rifino',
  'Ed Symon'],
 ['Leo Tover', 'Robert D. Webb', 'Stanley Hough'],
 ['Santosh Sivan'],
 ['Barry Sonnenfeld', 'Fred Murphy'],
 ['Jacques Haitkin', 'Steve De Jarnatt'],
 ['Rodrigo Prieto', 'Spike Lee'],
 ['Sean Penn', 'Eric Gautier', 'John R. Saunders', 'David Webb'],
 ['Kevin Smith', 'David Klein'],
 ['Chris Seager', 'Geoffrey Sax'],
 ['David Bowers'],
 ['Oliver Wood', 'Adam McKay'],
 ['Ric Waite', 'Dwight H. Little'],
 ['Greg Gardiner', 'Tom Dey'],
 ['Nora Ephron', 'John Lindley'],
 ['Kodi Rama Krishna', 'K.K. Senthil Kumar'],
 ['Michael Chapman', 'Ivan Reitman', 'David F. Klassen'],
 ['Michael Mann',
  'Dion Beebe',
  'Aran Mann',
  'Paul Cameron',
  'Gerald Sullivan',
  'Christopher Tandon',
  'Michael Waxman'],
 ['Peter Deming', 'Drew Goddard', 'Tom Reta', 'Chris Grun'],
 ['John Bailey', 'Richard LaGravenese'],
 ['C√©dric Klapisch', 'Christophe Beaucarne'],
 ['David Ayer', 'Roman Vasyanov'],
 ['Mac Ahlberg', 'Stuart Gordon'],
 ['M. Night Shyamalan',
  'Nicole Agostino',
  'Amy Lauritsen',
  'John Rusk',
  'Mike Gioulakis'],
 ['Reggie Rock Bythewood', 'Greg Gardiner'],
 ['Gary Goldman', 'Don Bluth', 'Dave Kupczyk'],
 ['Mike Newell', 'Michael Coulter'],
 ['Scott Frank', 'Scott Frank', 'Alar Kivilo'],
 ['Roger Deakins',
  'Joseph P. Reidy',
  'Charlie Revai',
  'Angelina Jolie',
  'Simon Christidis'],
 ['Francis Lawrence',
  'Dan Webster',
  'Jo Willems',
  'David Scheunemann',
  'Shaun Friedberg',
  'Carine Demongueres',
  'Sean Ryan Jennings',
  'Alice Leconte',
  "Justin O'Neal Miller",
  'Jade Mansueto',
  'Marlene Chazot',
  'Gunnar Zimmer'],
 ['Tom Shadyac', 'Dean Semler', 'Sally Thornton', 'Dawn Swiderski'],
 ['Andrzej Bartkowiak', 'Daryn Okada'],
 ['Fred Murphy', 'Paul Mazursky'],
 ['Ate de Jong', 'Robin Vidgeon'],
 ['Ron Underwood', 'Alexander Gruszynski'],
 ['Wesley Ruggles'],
 ['Martin Scorsese', 'Michael Ballhaus'],
 ['Spike Jonze'],
 ['Ben Affleck', 'Robert Richardson', 'Christa Munro', 'Bradley Rubin'],
 ['Shane Hurlbut', 'Charles Stone III'],
 ['Oliver Wood', 'Mark Waters'],
 ['Paul Sarossy', 'Atom Egoyan'],
 ['Xavier Dolan', 'Yves B√©langer'],
 ['Lance Rivera'],
 ['Brian Fee', 'Jeremy Lasky', 'Newton Thomas Sigel'],
 ['Clint Eastwood', 'Tom Stern', 'Donald Murphy'],
 ['Peter Lord', 'Jeff Newitt'],
 ['Catherine Ircha',
  'Neill Blomkamp',
  'Don MacAulay',
  'Trent Opaloch',
  'Luis Antonio Ordo√±ez',
  'Kent Matheson'],
 ['Shusuke Kaneko'],
 ['Peter Weir', 'John Seale'],
 ['Brendan Galvin', 'Tarsem Singh'],
 ['Alejandro Gonz√°lez I√±√°rritu',
  'Emmanuel Lubezki',
  'Isabelle Guay',
  'Michael Diner',
  'Chris Beach'],
 ['Brian Helgeland', 'Ericson Core', 'Mark Cotone'],
 ['Robert Benton'],
 ['Betty Thomas', 'Russell Boyd'],
 ['Donald E. Thorin',
  'Hugh Wilson',
  'Ed Check',
  'Paul D. Kelly',
  'Michael E. Steele',
  'Julie A. Bloom'],
 ['Olivier Megaton',
  'Romain Lacourbas',
  'Patrick Pasquier',
  'Sandro Valdez',
  'Anne Pelosi',
  'Eva Julhe'],
 ['Shana Feste'],
 ['George Miller',
  'Judy Morris',
  'Warren Coleman',
  'David Peers',
  'David Nelson',
  'P.J. Voeten',
  'Daniel Jeannette',
  'Brad Greenwood'],
 ['Teddy Chan'],
 ['Peter Lyons Collister', 'Bernie Goldmann', 'Melisa Wallack'],
 ['Craig Gillespie'],
 ['Larry Fong', 'Louis Leterrier', 'Mitchell Amundsen'],
 ['Danny Cannon', 'Michael Barrett'],
 ['James Wong Howe', 'Martin Ritt', 'James A. Rosenberger'],
 ['Gary Fleder', 'Aaron Schneider'],
 ['Kenneth Branagh', 'Stuart Kearns', 'Haris Zambarloukos'],
 ['David Frankel', 'Maryse Alberti'],
 ['Hayao Miyazaki',
  'Shigeharu Shiba',
  'Kazuyoshi Katayama',
  'Kazuo Komatsubara',
  'Takashi Tanazawa'],
 ['Zana Briski', 'Ross Kauffman'],
 ['Enrique Chediak',
  'Marc Fisichella',
  'Peter Berg',
  'Brittany Loar',
  'Lauren Slatten'],
 ['Guy Hamilton', 'Ted Moore'],
 ['DJ Pooh'],
 ['Lexi Alexander',
  'Vincent Gingras-Liberali',
  'Charlotte Rouleau',
  'Guy Pigeon'],
 ['Seamus McGarvey',
  'Breck Eisner',
  'Marc Homes',
  'John Marzano',
  'Christopher Newman'],
 ['Roger Allers', 'Rob Minkoff'],
 ['Paul W.S. Anderson', 'David Tattersall', 'Paul Sonski', 'Melanie J. Baker'],
 ['Peter Jackson', 'Andrew Lesnie'],
 ['Hari', 'Priyan'],
 ['Renat Davletyarov', 'Semyon Yakovlev'],
 ['Jacques Audiard', 'St√©phane Fontaine'],
 ['Michael Mann',
  'Dante Spinotti',
  'Margie Stone McShirley',
  'Erik Olson',
  'Steven Schwartz',
  'Michael Waxman'],
 ['Randall Wallace', 'Dean Semler'],
 ['David Gelb', 'Michael Fimognari'],
 ['Anees Bazmee'],
 ['John Moore', 'Patrick Lumb', 'Brendan Galvin'],
 ['Martin Scorsese', 'Michael Ballhaus'],
 ["John 'Bud' Cardos", 'John Arthur Morrill'],
 ['Stephen Goldblatt', 'Peter Hyams'],
 ['Norton Virgien', 'Igor Kovalyov'],
 ['Joel Coen', 'Barry Sonnenfeld', 'Gregory Jacobs'],
 ['Gary Chapman'],
 ['Edward Zwick',
  'Eduardo Serra',
  'Peter Wenham',
  'Ray Chan',
  'Sarah Moudjebeur'],
 ['Jean-Jacques Annaud', 'Jean-Marie Dreujou'],
 ['John Dahl', 'Marc Reshovsky'],
 ['Oliver Stone', 'Salvatore Totino'],
 ['Steve Bendelack', 'Baz Irvine'],
 ['Hector Babenco', 'Lauro Escorel'],
 ['Steve Gainer', 'Mike Gunther'],
 ['Donald McAlpine', 'Peter Segal'],
 ['Alessandro Genovesi'],
 ['Dmitriy Kiselev'],
 ['Brian Levant', 'Victor J. Kemper'],
 ['Michael C. Butler', 'Hal Needham'],
 ['Michael Mann',
  'Dante Spinotti',
  'Dennis Bradford',
  'Erik Olson',
  'Patricia Woodbridge'],
 ['John Waters', 'Robert M. Stevens'],
 ['John Bailey', 'Gary David Goldberg'],
 ['Rajkumar Santoshi', 'A.R. Rahman'],
 ['Jim Gillespie', 'Denis Crossan', 'Steve Mirkovich', "Louis D'Esposito"],
 ['John A. Alonzo', 'Ralph Bakshi'],
 ['Robert Richardson', 'Oliver Stone', 'Seth Cirker'],
 ['Tim Suhrstedt', 'Stephen Herek'],
 ['James Cameron', 'Adrian Biddle', 'Terry Ackland-Snow'],
 ['Gary Ross', 'John Schwartzman', 'Michael Scheffe'],
 ['Lasse Hallstr√∂m', 'Terry Stacey'],
 ['Martin Koolhoven'],
 ['Larry Charles'],
 ['Simon West', 'Peter Menzies Jr.'],
 ['Elliot Davis', 'Catherine Hardwicke'],
 ['Ashwani Dhir', 'Tushar Hiranandani'],
 ['Woody Allen', 'Darius Khondji', 'Sid Karne', 'Gil Kenny'],
 ['Andrew Laszlo', 'Brian Gibson', 'John Bruno'],
 ['Scott Sanders'],
 ['James McTeigue', 'Frank Walsh', 'Danny Ruhlmann'],
 ['Anthony Byrne'],
 ['Fred Savage'],
 ['Peter Weir', 'Russell Boyd'],
 ['Christopher Nolan', 'Wally Pfister', 'Alan B. Curtiss'],
 ['Richard Linklater', 'Shane F. Kelly'],
 ['Matthew F. Leonetti',
  'Lon Bender',
  'Eric Bress',
  'J. Mackye Gruber',
  'Geoffrey G. Rubay',
  'Peter D. Marshall',
  'Cindy Smith',
  'Lori K. Peterson'],
 ['Kathryn Bigelow', 'Adrian Biddle'],
 ['Gore Verbinski', 'Dariusz Wolski'],
 ['M. David Mullen', 'Michael Polish'],
 ['Remi Adefarasin', 'Peter Howitt'],
 ['Ron Shelton', 'Bobby Byrne'],
 ['Kleber Mendon√ßa Filho', 'Pedro Sotero', 'Fabricio Tadeu\t'],
 ['Simon Duggan', 'Sue Chan', 'Noam Murro'],
 ['Nicole Garcia', 'Christophe Beaucarne', 'S√©bastien Matuchet'],
 ['Peter Hyams', 'John Hyams'],
 ['Andrew Lesnie', 'Chris Noonan'],
 ['Peter Kohn',
  'Michael Ballhaus',
  'Wolfgang Petersen',
  'Nancy Patton',
  'David B. Nowell'],
 ['Peter Hyams', 'Peter Hyams'],
 ['Ashley Rowe', 'Andy Cadiff'],
 ['Anthony Hickox', 'Gerry Lively'],
 ['Alfred Hitchcock', 'George Barnes', 'Edmond F. Bernoudy', 'Eric Stacey'],
 ['Tom Kalin'],
 ['Kirk Jones'],
 ['Robert Rodriguez', 'Guillermo Navarro'],
 ['Greg Gardiner', 'Andy Fickman'],
 ['Robert Zemeckis',
  'Don Burgess',
  'Doug J. Meerdink',
  'Sally Thornton',
  'Brad Ricker',
  'Bruce Moriarty',
  'Martin A. Kline'],
 ['Patrick Read Johnson'],
 ['Sylvester Stallone', 'Bill Butler'],
 ['Mark Irwin', 'Joe Nussbaum'],
 ['Christophe Beaucarne', 'Anne Fontaine'],
 ['Lawrence Sher', 'Todd Phillips'],
 ['John Lindley', 'Joseph Ruben'],
 ['Stefan Ruzowitzky'],
 ['Inna Evlannikova', 'Svyatoslav Ushakov'],
 ['Howard Deutch'],
 ['Lorene Scafaria', 'Brett Pawlak'],
 ['David Eggby', 'John Bonito'],
 ['Himman Dhamija', 'Nikhil Advani'],
 ['Miroslav Ond≈ô√≠ƒçek', 'Penny Marshall'],
 ['Roland Emmerich', 'Markus F√∂rderer'],
 ['Robert Redford',
  'Newton Thomas Sigel',
  'Geoffrey S. Grimsman',
  'Alex Laurent'],
 ['Robert Redford', 'Robert Richardson'],
 ['Ilya Maksimov'],
 ['James DeMonaco', 'Jacques Jouffret'],
 ['Todd Haynes'],
 ['Adam Elliot', 'Gerald Thompson'],
 ['Philippe Rousselot', 'Robert Redford'],
 ['Stefan Ruzowitzky', 'Shane Hurlbut', 'F√©lix Larivi√®re-Charron'],
 ['Anders Anderson'],
 ['David Hogan'],
 ['Justin Barber', 'Jay Keitel'],
 ['Mark Irwin', 'Kevin Hooks'],
 ['Genndy Tartakovsky'],
 ['John Toll', 'Cameron Crowe'],
 ['Spike Lee'],
 ['St√©phane Rybojad'],
 ['Barry Levinson', 'St√©phane Fontaine'],
 ['Stuart Baird',
  'Andrzej Bartkowiak',
  'Kurt E. Soderling',
  'David W. Krummel',
  'Vincent Lascoumes'],
 ['Darren Aronofsky', 'Matthew Libatique'],
 ['Gr√©gory Levasseur', 'Laurent Tangy', 'Heidi El Ayoubi'],
 ['Elia Kazan', 'Boris Kaufman'],
 ['Lasse Hallstr√∂m', 'Terry Stacey'],
 ['Peter Hyams', 'Peter Hyams'],
 ['David Koepp', 'Fred Murphy'],
 ['Mani Ratnam', 'P. C. Sreeram'],
 ['James Marsh',
  'Beno√Æt Delhomme',
  'Kira Kemble',
  'Deborah Saban',
  'David Hindle'],
 ['Paul Thomas Anderson', 'Mihai Malaimare Jr.', 'Adam Somner'],
 ['Peter Howitt', 'John Bailey'],
 ['Tim Burton', 'Bruno Delbonnel'],
 ['Michael D. Moore',
  'Cecil B. DeMille',
  'Loyal Griggs',
  'Daniel McCauley',
  'Francisco Day',
  'Edward Salven'],
 ['Julian Gilbey', 'Ali Asad'],
 ['Thomas Bezucha', 'Jonathan Brown'],
 ['Peter Deming', 'Marco Schnabel'],
 ['Robert Elswit', 'Tony Gilroy', 'Steve Apicella'],
 ['Dean Semler', 'Donald Petrie'],
 ['Henry Koster', 'Leon Shamroy'],
 ['Harry Winer'],
 ['Gyula Pados',
  'Nimr√≥d Antal',
  'Sean Noel Walker',
  'Brian Bettwy',
  'jonathan Swartz'],
 ['Rod Hardy', 'David Connell'],
 ['Matthew Libatique', 'Spike Lee'],
 ['Martin Lawrence', 'Daryn Okada', 'David Raynr'],
 ['Michael Bay', 'John Schwartzman'],
 ['Steven Spielberg', 'Douglas Slocombe', 'Artist W. Robinson'],
 ['Joe Wright', 'John Mathieson', 'Seamus McGarvey'],
 ['Richard Linklater', 'Lee Daniel'],
 ['Danny Cannon', 'Vernon Layton', 'Enrique Echeverr√≠a', "Louis D'Esposito"],
 ['Peter Jackson', 'Andrew Lesnie'],
 ['Bob Fosse', 'Robert Surtees'],
 ['Christian Sebaldt', 'Preston A. Whitmore II', 'Regina Gordon'],
 ['Alexander Payne', 'James Glennon'],
 ['John Harrison', 'Robert Draper'],
 ['Mike Flanagan'],
 ['Matthew Libatique', 'Joel Schumacher'],
 ['Neill Blomkamp', 'Trent Opaloch'],
 ['Mathieu Kassovitz',
  'Matthew Libatique',
  'Nicolas Lepage',
  'Jim Kaufman',
  'Pete Romano',
  'Pierre Brassard',
  'Nadine Brassard'],
 ['Rintaro', 'Hitoshi Yamaguchi'],
 ['Anastas N. Michos', 'David E. Talbert'],
 ['Dexter Fletcher'],
 ['Carroll Ballard', 'Caleb Deschanel'],
 ['Jack Green',
  'Donald B. Woodruff',
  'Peter Segal',
  'Hans Bjerno',
  'Laura Weiss',
  'Adam Druxman',
  'Joseph J. Kontra'],
 ['Karen Schulz Gropman', 'John Frankish', 'John Wells', 'Adriano Goldman'],
 ['John Wayne', 'William H. Clothier'],
 ['James Whitaker', 'Julie Anne Robinson'],
 ['Denise Di Novi',
  'Caleb Deschanel',
  'Jonas Spaccarotelli',
  'Ravi D. Mehta',
  'Steven Ritzi',
  'Deborah Chung'],
 ['Marshall Brickman', 'Billy Williams'],
 ['Anthony Dod Mantle', 'Danny Boyle', 'Mark Digby'],
 ['Rob Zombie',
  'Tom Richmond',
  'Alex Poppas',
  'Erin Smith',
  'Marco Black',
  'Ty Arnold'],
 ['Martin Campbell', 'Phil Meheux', 'Greg Berry', 'Ron Mason'],

In [152]:
ROI4=pd.DataFrame((df4['revenue']-df4['budget'])/df4['budget'],columns=['profit'])     #so this is the row which has max revenue we will analyse it more

In [153]:
len(producer4)

2152

In [154]:
len(director4)

2152

In [155]:
len(ROI4)

2152

In [156]:
df4['producer']=producer4
df4['director']=director4
df4['ROI']=ROI4

In [157]:
type(df4['producer'][0])

list

In [158]:
table=pd.DataFrame({"producer":df4['producer'],"director":df4['director'],"ROI":df4['ROI']})

In [159]:
table

,producer,director,ROI
0,[Andrew Panay],"[Kelly Cantley, Steve Pink, Declan Quinn, Josh...",-0.120382
1,"[Whitney Houston, Mario Iscovich, Debra Martin...","[Garry Marshall, Charles Minsky]",1.378736
2,"[David Lancaster, Michel Litvak, Jason Blum, H...","[Sharone Meir, Damien Chazelle, Nicolas Duchem...",2.967273
3,[Sujoy Ghosh],[Sujoy Ghosh],12.333333
5,[],[Hal Sutherland],-0.592295
...,...,...,...
2976,[Douglas Fairbanks],"[Arthur Edeson, Raoul Walsh, James T. O'Donoho...",0.068882
2977,"[Steven Spielberg, Walter F. Parkes, Laurie Ma...","[Steven Spielberg, Janusz Kami≈Ñski]",2.656954
2981,"[Stephanie Austin, Shane Black, Renny Harlin, ...","[Renny Harlin, Guillermo Navarro]",0.376258
2982,"[Danny DeVito, Michael Shamberg, Stacey Sher]","[Seamus McGarvey, John Hamburg, Daniel Silverb...",3.094366
2983,"[Doug Davison, Roy Lee, Ellen Goldsmith-Vein, ...","[John Singleton, Peter Menzies Jr., Jay Durrwa...",1.345347

In [160]:
table=table.explode("producer")

In [161]:
table.groupby("producer")["ROI"].mean().sort_values(ascending=False).head(3)

producer
Amir Zbeda     12889.386667
Robin Cowie     4132.333333
Gregg Hale      4132.333333
Name: ROI, dtype: float64

#question 5: Top 3 directors prefer which actors the most?

In [162]:
df5=data.dropna(subset=['cast','crew']).reset_index(drop=True)

In [163]:
df5=df5[df5['budget']>10000]

In [164]:
df5['crew']=df5['crew'].apply(convert)

In [165]:
df5['cast']=df5['cast'].apply(convert)

In [166]:
df5['cast'][0]

[{'cast_id': 4,
  'character': 'Lou',
  'credit_id': '52fe4ee7c3a36847f82afae7',
  'gender': 2,
  'id': 52997,
  'name': 'Rob Corddry',
  'order': 0,
  'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'},
 {'cast_id': 5,
  'character': 'Nick',
  'credit_id': '52fe4ee7c3a36847f82afaeb',
  'gender': 2,
  'id': 64342,
  'name': 'Craig Robinson',
  'order': 1,
  'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'},
 {'cast_id': 6,
  'character': 'Jacob',
  'credit_id': '52fe4ee7c3a36847f82afaef',
  'gender': 2,
  'id': 54729,
  'name': 'Clark Duke',
  'order': 2,
  'profile_path': '/oNzK0umwm5Wn0wyEbOy6TVJCSBn.jpg'},
 {'cast_id': 7,
  'character': 'Adam Jr.',
  'credit_id': '52fe4ee7c3a36847f82afaf3',
  'gender': 2,
  'id': 36801,
  'name': 'Adam Scott',
  'order': 3,
  'profile_path': '/5gb65xz8bzd42yjMAl4zwo4cvKw.jpg'},
 {'cast_id': 8,
  'character': 'Hot Tub Repairman',
  'credit_id': '52fe4ee7c3a36847f82afaf7',
  'gender': 2,
  'id': 54812,
  'name': 'Chevy Chase',
  'order': 4,
  'profile_path': '/svjpyYtPwtjvRxX9IZnOmOkhDOt.jpg'},
 {'cast_id': 9,
  'character': 'Jill',
  'credit_id': '52fe4ee7c3a36847f82afafb',
  'gender': 1,
  'id': 94098,
  'name': 'Gillian Jacobs',
  'order': 5,
  'profile_path': '/rBnhe5vhNPnhRUdtYahBWx90fJM.jpg'},
 {'cast_id': 10,
  'character': 'Sophie',
  'credit_id': '52fe4ee7c3a36847f82afaff',
  'gender': 1,
  'id': 1159009,
  'name': 'Bianca Haase',
  'order': 6,
  'profile_path': '/4x3nbtD8q8phAJPmoGWXPvz0iM.jpg'},
 {'cast_id': 11,
  'character': 'Kelly',
  'credit_id': '5524ec51c3a3687df3000dbb',
  'gender': 1,
  'id': 86624,
  'name': 'Collette Wolfe',
  'order': 7,
  'profile_path': '/aSD4h5379b2eEw3bLou9ByLimmq.jpg'},
 {'cast_id': 13,
  'character': 'Brad',
  'credit_id': '5524ec8ec3a3687ded000d72',
  'gender': 2,
  'id': 466505,
  'name': 'Kumail Nanjiani',
  'order': 9,
  'profile_path': '/x4nAztHY72SVciRfxEsbhIVTsIu.jpg'},
 {'cast_id': 14,
  'character': 'Courtney',
  'credit_id': '5524ec9bc3a3687df8000d13',
  'gender': 1,
  'id': 70776,
  'name': 'Kellee Stewart',
  'order': 10,
  'profile_path': '/w3xmsEPmJc1Cf0dQ4aIn8YmlHbk.jpg'},
 {'cast_id': 15,
  'character': 'Terry',
  'credit_id': '5524eca892514171cb008237',
  'gender': 2,
  'id': 347335,
  'name': 'Josh Heald',
  'order': 11,
  'profile_path': '/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg'},
 {'cast_id': 16,
  'character': 'Susan',
  'credit_id': '5524ecb7925141720c001116',
  'gender': 0,
  'id': 1451392,
  'name': 'Gretchen Koerner',
  'order': 12,
  'profile_path': '/muULPexCTJGyJba4yKzxronpD50.jpg'},
 {'cast_id': 17,
  'character': 'Herself',
  'credit_id': '5524ecc3c3a3687ded000d74',
  'gender': 1,
  'id': 98879,
  'name': 'Lisa Loeb',
  'order': 13,
  'profile_path': '/bGqg58ca0bZR38z9HliUMmeNGE.jpg'},
 {'cast_id': 18,
  'character': 'Herself',
  'credit_id': '5524ecd3c3a3687e11000ed3',
  'gender': 1,
  'id': 1394648,
  'name': 'Jessica Williams',
  'order': 14,
  'profile_path': '/A4syKjkcYB92wLEhH0c0hC3BCpz.jpg'},
 {'cast_id': 19,
  'character': 'Himself',
  'credit_id': '5524ece6925141718d001009',
  'gender': 0,
  'id': 1451393,
  'name': 'Bruce Buffer',
  'order': 15,
  'profile_path': None},
 {'cast_id': 20,
  'character': 'Shot Girl',
  'credit_id': '5524ecf5c3a3687e08000dc2',
  'gender': 0,
  'id': 1451394,
  'name': 'Mariana Paola Vicente',
  'order': 16,
  'profile_path': '/ckPllza8624UHWGHCbLShkLxCD1.jpg'},
 {'cast_id': 33,
  'character': 'Choozy Doozy Host',
  'credit_id': '555844da9251412afe0013a9',
  'gender': 2,
  'id': 2224,
  'name': 'Christian Slater',
  'order': 17,
  'profile_path': '/3ElLWjnvchMS6Q4cIQOK8QNAoMG.jpg'},
 {'cast_id': 35,
  'character': 'Gary Winkle',
  'credit_id': '55872027c3a3683853005074',
  'gender': 0,
  'id': 185805,
  'name': 'Jason Jones',
  'order': 18,
  'profile_path': '/aIoCw6vo8AGMdsQRAI5g2t0yJT3.jpg'},
 {'cast_id': 36,
  'character': 'Bridesmaid',
  'credit_id': '55efe971c3a368090c00cd1b',
  'gender': 0,
  'id': 1507448,
  'name': 'Olivia Jordan',
  'order': 19,
  'profile_path': '/szMukAEiIDeasel0lvyaeyKuych.jpg'},
 {'cast_id': 37,
  'character': 'Christine',
  'credit_id': '55efe980c3a36871bf008176',
  'gender': 1,
  'id': 1334091,
  'name': 'Christine Bently',
  'order': 20,
  'profile_path': '/oUZltnGa55OXE52hfyPTfCshuNy.jpg'},
 {'cast_id': 38,
  'character': 'Excited Girl',
  'credit_id': '55efe98e9251413e3201d316',
  'gender': 0,
  'id': 557803,
  'name': 'Stacey Asaro',
  'order': 21,
  'profile_path': '/qTPdlr1dXf3kNdyHuDsgtGC0HCC.jpg'},
 {'cast_id': 64,
  'character': 'Adam (uncredited)',
  'credit_id': '58f2135ac3a3682e95008b91',
  'gender': 2,
  'id': 3036,
  'name': 'John Cusack',
  'order': 22,
  'profile_path': '/uKydQYuZ9TnCzvbQLtj6j98vWAT.jpg'},
 {'cast_id': 65,
  'character': 'J-Bird',
  'credit_id': '59ac0240c3a3682cc802c399',
  'gender': 2,
  'id': 59256,
  'name': 'Adam Herschman',
  'order': 23,
  'profile_path': '/wZMwiuX1DslF6hDS50z9OTN6z1X.jpg'},
 {'cast_id': 66,
  'character': 'Bridesmaid',
  'credit_id': '59ac02cd925141079d02b1b4',
  'gender': 1,
  'id': 129714,
  'name': 'Kisha Sierra',
  'order': 24,
  'profile_path': None}]

In [167]:
actor5=[]
for i in range(len(df5['cast'])):
  l=[]
  for j in range(len(df5['cast'].iloc[i])):
    l.append(df5['cast'].iloc[i][j]["name"])
  actor5.append(l)

In [168]:
actor5

[['Rob Corddry',
  'Craig Robinson',
  'Clark Duke',
  'Adam Scott',
  'Chevy Chase',
  'Gillian Jacobs',
  'Bianca Haase',
  'Collette Wolfe',
  'Kumail Nanjiani',
  'Kellee Stewart',
  'Josh Heald',
  'Gretchen Koerner',
  'Lisa Loeb',
  'Jessica Williams',
  'Bruce Buffer',
  'Mariana Paola Vicente',
  'Christian Slater',
  'Jason Jones',
  'Olivia Jordan',
  'Christine Bently',
  'Stacey Asaro',
  'John Cusack',
  'Adam Herschman',
  'Kisha Sierra'],
 ['Anne Hathaway',
  'Julie Andrews',
  'H√©ctor Elizondo',
  'John Rhys-Davies',
  'Heather Matarazzo',
  'Chris Pine',
  'Callum Blue',
  'Larry Miller',
  'Raven-Symon√©',
  'Kathleen Marshall',
  'Caroline Goodall',
  'Lorraine Nicholson',
  'Shannon Wilcox',
  'Greg Lewis',
  'Abigail Breslin',
  'Paul Vogt',
  'Joseph Leo Bwarie',
  'Hope Alexander-Willis',
  'Rowan Joseph',
  'Jeffrey Scott Jensen'],
 ['Miles Teller',
  'J.K. Simmons',
  'Melissa Benoist',
  'Austin Stowell',
  'Jayson Blair',
  'Kavita Patil',
  'Paul Reiser',
  'Nate Lang',
  'Chris Mulkey',
  'Damon Gupton',
  'Suanne Spoke',
  'Max Kasch',
  'Charlie Ian',
  'Kofi Siriboe',
  'C.J. Vana',
  'Tarik Lowe',
  'Tyler Kimball',
  'Rogelio Douglas Jr.',
  'Adrian Burks',
  'Joseph Bruno',
  'Michael D. Cohen',
  'Jocelyn Ayanna',
  'Keenan Henson',
  'Janet Hoskins',
  'April Grace',
  "Clifton 'Fou Fou' Eddie",
  'Calvin C. Winbush',
  'Marcus Henderson',
  'Tony Baker',
  'Henry G. Sanders',
  'Sam Campisi',
  'Jimmie Kirkpatrick',
  'Keenan Allen',
  'Ayinde Vaughan',
  'Shai Golan',
  'Yancey Wells',
  'Candace Roberge',
  'Krista Kilber',
  'Cici Leah Campbell',
  'Damien Coates',
  'Kyle Julian Graham',
  'Ellee Jane Hounsell',
  'Stephen Hsu',
  'Herman Johansen',
  'Wendee Lee',
  'Dakota Lupo',
  'Jesse Mitchell',
  'Amanda Newman',
  'Joseph Oliveira',
  'Michelle Ruff',
  'Daniel Weidlein'],
 ['Vidya Balan',
  'Nawazuddin Siddiqui',
  'Parambrata Chatterjee',
  'Saswata Chatterjee',
  'Indraneil Sengupta',
  'Darshan Jariwala',
  'Masood Akhtar'],
 ['Scott Grimes', 'Tom Bosley', 'Rickie Lee Jones', 'James Earl Jones'],
 ['Jeffrey Dean Morgan',
  'Natasha Calis',
  'Madison Davenport',
  'Kyra Sedgwick',
  'Rob LaBelle',
  'Nana Gbewonyo ',
  'Jim Thorburn ',
  'Matisyahu ',
  'Quinn Lord',
  'Jay Brazeau',
  'Erin Simms',
  'John Cassini',
  'Grant Show',
  'Tim Perez'],
 ['Bob Balaban',
  'Christopher Guest',
  'John Michael Higgins',
  'Eugene Levy',
  'Jane Lynch',
  'Michael McKean',
  "Catherine O'Hara",
  'Parker Posey',
  'Harry Shearer',
  'Fred Willard',
  'Larry Miller',
  'Ed Begley Jr.',
  'Rachael Harris',
  'Jennifer Coolidge',
  'Paul Dooley',
  'Don Lake',
  'Deborah Theaker',
  'Bill Cobbs',
  'Michael Mantell',
  'Michael Hancock'],
 ['Sylvester Stallone',
  'Talia Shire',
  'Burt Young',
  'Carl Weathers',
  'Burgess Meredith',
  'Thayer David',
  'Joe Spinell',
  'Tony Burton',
  'Joe Frazier',
  'Jimmy Gambina',
  'Jodi Letizia',
  'Stan Shaw',
  'Michael Dorn',
  'DeForest Covan',
  'Bill Baldwin',
  'Lloyd Kaufman',
  'Al Silvani',
  'George Memmoli',
  'Diana Lewis',
  "George O'Hanlon",
  'Larry Carroll',
  'Frank Stallone',
  'Don Sherman',
  'Billy Sands',
  'Simmy Bow',
  'Jane Marla Robbins',
  'Frank Pesce',
  'John Pleshette',
  'Lavelle Roby',
  'Pedro Lovell',
  'Stu Nahan',
  'Hank Rolike',
  "Shirley O'Hara",
  'Kathleen Parker',
  'Frankie Van',
  'Arnold Johnson',
  'Arthur Tovey'],
 ['Kevin Spacey',
  'Annette Bening',
  'Thora Birch',
  'Wes Bentley',
  'Mena Suvari',
  'Chris Cooper',
  'Scott Bakula',
  'Peter Gallagher',
  'Allison Janney',
  'Sam Robards',
  'Barry Del Sherman',
  'John Cho',
  'Hal Fort Atkinson',
  'Kent Faulcon',
  'Ara Celi',
  'Sue Casey',
  'Brenda Wehle',
  'Lisa Cloud',
  'Amber Smith',
  'Joel McCrary',
  'Marissa Jaret Winokur',
  'Dennis Anderson',
  'Matthew Kimbrough',
  'Erin Cathryn Strubbe',
  'Alison Faulk',
  'Krista Goodsitt',
  'Lily Houtkin',
  'Carolina Lancaster',
  'Mona Leah',
  'Chekesha Van Putten',
  'Emily Zachary',
  'Nancy Anderson',
  'Reshma Gajjar',
  'Stephanie Rizzo',
  'Heather Joy Sher',
  'Chelsea Hertford',
  'Elaine Corral Kendall',
  'David C. Fisher',
  'Tom Miller',
  'Bruce Cohen'],
 ['John Travolta',
  'Uma Thurman',
  'Vince Vaughn',
  'Cedric the Entertainer',
  'Andr√© Benjamin',
  'Steven Tyler',
  'Robert Pastorelli',
  'Christina Milian',
  'Paul Adelstein',
  'Debi Mazar',
  'Gregory Alan Williams',
  'Harvey Keitel',
  'Dwayne Johnson',
  'Danny DeVito',
  'James Woods',
  'Anthony J. Ribustello',
  'Wyclef Jean',
  'Fred Durst',
  'S√©rgio Mendes',
  'Gene Simmons',
  'RZA',
  'Joe Perry',
  'Anna Nicole Smith',
  'Alex Kubik',
  'Darren Carter',
  'Carol Duboc',
  'Minae Noji',
  'Arielle Kebbel',
  'Kimberly J. Brown',
  'Margaret Travolta',
  'Scott Adsit',
  'Brian Christensen',
  'Nick Loren',
  'Craig Susser',
  'George Fisher',
  'Sahar Simmons',
  'Serdar Kalsin',
  'Russ Irwin',
  'Joey Kramer',
  'Brad Whitford',
  'Tom Hamilton',
  'Joyce Tolbert',
  'Noelle Scaggs',
  'Will.i.am',
  'Fergie',
  'Apl.de.Ap ',
  'Taboo',
  'Carmen Getit',
  'Steve Lucky',
  'Kimberly Wyatt',
  'Kasey Campbell',
  'Ashley Roberts',
  'Nicole Scherzinger',
  'Shanell Woodgett',
  'Clifford McGhee',
  'Christopher Toler',
  "Ivan 'Flipz' Velez",
  'Donyelle Denise Jones',
  'Gustavo Vargas'],
 ['Tom Cruise',
  'Colin Farrell',
  'Samantha Morton',
  'Max von Sydow',
  'Lois Smith',
  'Peter Stormare',
  'Tim Blake Nelson',
  'Steve Harris',
  'Kathryn Morris',
  'Mike Binder',
  'Daniel London',
  'Neal McDonough',
  'Jessica Capshaw',
  'Patrick Kilpatrick',
  'Jessica Harper',
  'Ashley Crow',
  'Arye Gross',
  'Fiona Hale',
  'George Wallace',
  'Frank Grillo',
  'Cameron Diaz',
  'William Mapother',
  'Jason Antoon'],
 ['Nikola Rakoƒçeviƒá',
  'Viktor Saviƒá',
  'Nata≈°a Tapu≈°koviƒá',
  'Nikola Kojo',
  'Bojana Novakoviƒá',
  'Dragan Miƒáanoviƒá',
  'Srƒëan Miletiƒá',
  'Predrag Ejdus',
  "Milan 'Caci' Mihailoviƒá",
  'Branislav Jevic',
  'Jasmina Avramoviƒá',
  'Dimitrije Vojnov',
  'Nikola Gli≈°iƒá'],
 ['Rachel McAdams',
  'Cillian Murphy',
  'Brian Cox',
  'Jayma Mays',
  'Jack Scalia',
  'Robert Pine',
  'Terry Press',
  'Brittany Oaks',
  'Laura Johnson',
  'Max Kasch',
  'Kyle Gallner',
  'Angela Paton',
  'Loren Lester',
  'Suzie Plakson',
  'Monica McSwain',
  'Beth Toussaint',
  'Adam Gobble',
  'Megan Crawford',
  'Carl Gilliard',
  'Mary Kathleen Gordon',
  'Philip Pavel',
  'Amber Mead',
  'Dey Young',
  'Jeanine Jackson'],
 ['Felicity Jones',
  'Ed Westwick',
  'Brooke Shields',
  'Bill Nighy',
  'Tamsin Egerton',
  'Bill Bailey',
  'Sophia Bush',
  'Nicholas Braun',
  'Georgia King',
  'Tom Goodman-Hill',
  'Gregor Blo√©b',
  'Adam Bousdoukos',
  'Ken Duken',
  'Jo Martin',
  'Rebecca Lacey',
  'Chandra Ruegg',
  'Alex MacQueen',
  'Mike Goodenough',
  'Steve Furst',
  'Graham Lee',
  'Tara Dakides',
  'Abbie Dunn',
  'Patrick Finger'],
 ['Jason Statham',
  'Amber Valletta',
  'Kate Nauta',
  'Alessandro Gassman',
  'Fran√ßois Berl√©and',
  'Robert Small',
  'Matthew Modine',
  'Jason Flemyng',
  'Keith David',
  'Ron Madoff'],
 ['Gary Oldman',
  'William Hurt',
  'Matt LeBlanc',
  'Mimi Rogers',
  'Heather Graham',
  'Lacey Chabert',
  'Jack Johnson',
  'Jared Harris',
  'Mark Goddard',
  'Lennie James',
  'Marta Kristen',
  'June Lockhart',
  'Adam Sims',
  'Angela Cartwright',
  'John Sharian',
  'Abigail Canton',
  'Richard Saperstein',
  'Dick Tufeld',
  'Gary A. Hecker',
  'Edward Fox'],
 ['Dana Kimmell',
  'Paul Kratka',
  'Tracie Savage',
  'Jeffrey Rogers',
  'Catherine Parks',
  'Larry Zerner',
  'Rachel Howard',
  'David Katims',
  'Nick Savage',
  'Gloria Charles',
  "Kevin O'Brien",
  'Richard Brooker',
  'Steve Susskind',
  'David Wiley',
  'Perla Walter',
  'Anne Gaybis'],
 ['Steve Martin',
  'Campbell Scott',
  'Ben Gazzara',
  'Rebecca Pidgeon',
  'Ricky Jay',
  'Felicity Huffman'],
 ['Daniel Radcliffe',
  'Zoe Kazan',
  'Rafe Spall',
  'Megan Park',
  'Adam Driver',
  'Jemima Rooper',
  'Meghan Heffern',
  'Jordan Hayes',
  'Mackenzie Davis',
  'Vanessa Matsui',
  'Sarah Gadon',
  'Lucius Hoyos',
  'Tommie-Amber Pirie',
  'Jonathan Cherry',
  'Rebecca Northan',
  'Oona Chaplin',
  'Adam Fergus',
  'Sam Moses',
  'Ennis Esmer',
  'Mike Wilmot',
  'George Tchortov',
  'Tamara Duarte',
  'Rosalind Feldman',
  'Don Ritter'],
 ['Judd Nelson',
  'Peter Cullen',
  'Frank Welker',
  'Leonard Nimoy',
  'Orson Welles',
  'Eric Idle',
  'Robert Stack',
  'Norman Alden',
  'Jack Angel',
  'Michael Bell',
  'Gregg Berger',
  'Susan Blu',
  'Lionel Stander',
  'John Moschitta, Jr.',
  'Buster Jones',
  'Paul Eiding',
  'Neil Ross',
  'Scatman Crothers',
  'Casey Kasem',
  'Dan Gilvezan',
  'Corey Burton',
  'Roger C. Carmel',
  'Stanley Jones',
  'Chris Latta',
  'Arthur Burghardt',
  'Roger C. Carmel',
  'Don Messick',
  'Corey Burton',
  'Ed Gilbert',
  'Clive Revill',
  'Hal Rayle',
  'David Mendenhall',
  'Victor Caroli'],
 ['Ben Affleck',
  'Samuel L. Jackson',
  'Kim Staunton',
  'Toni Collette',
  'Sydney Pollack',
  'Matt Malloy',
  'William Hurt',
  'John Benjamin Hickey',
  'Amanda Peet',
  'Michael Pitt',
  'Myra Lucretia Taylor'],
 ['Fran√ßois Cluzet',
  'Omar Sy',
  'Audrey Fleurot',
  'Anne Le Ny',
  'Clotilde Mollet',
  'Alba Ga√Øa Kraghede Bellugi',
  'Cyril Mendy',
  'Christian Ameri',
  'Marie-Laure Descoureaux',
  'Salimata Kamate',
  'Absa Diatou Toure',
  'Dominique Daguier',
  'Fran√ßois Caron',
  'Thomas Soliv√©res',
  'Gr√©goire Oestermann',
  'Doroth√©e Bri√®re',
  'Jos√©phine de Meaux',
  'Emilie Caen',
  'Caroline Bourg',
  'Sylvain Lazard',
  'Jean-Fran√ßois Cayrey',
  'Ian Fenelon',
  'Renaud Barse',
  'Fran√ßois Bureloup',
  'Nicky Marbot',
  'Benjamin Baroche',
  'J√©r√¥me Pauwels',
  'Antoine Laurent',
  'Fabrice Mantegna',
  'Hedi Bouchenafa',
  'Michel Winogradoff',
  'Elliot Latil'],
 ['Vin Diesel',
  'Rose Leslie',
  'Elijah Wood',
  '√ìlafur Darri √ìlafsson',
  'Rena Owen',
  'Julie Engelbrecht',
  'Michael Caine',
  'Joseph Gilgun',
  'Isaach De Bankol√©',
  'Sloane Coombs',
  'Dawn Olivieri',
  'Inbar Lavi',
  'Bex Taylor-Klaus',
  'Aimee Carrero',
  'Armani Jackson',
  'Samara Lee',
  'Stephanie Bertoni',
  'Kurt Angle',
  'David Whalen',
  'Jack Erdie',
  'Toussaint Raphael Abessolo',
  'Allegra Carpenter'],
 ['Chris Tucker',
  'Jackie Chan',
  'Hiroyuki Sanada',
  'Max von Sydow',
  'Yvan Attal',
  'Roman Polanski',
  'Zhang Jingchu',
  'Philip Baker Hall',
  'No√©mie Lenoir',
  'Sarah Shahi',
  'Youki Kudoh',
  'Tzi Ma',
  'Dana Ivey',
  'Henry O',
  'Mia Tyler',
  'Michael Chow',
  'Kentaro',
  'Ann Christine'],
 ['Jason Statham',
  'Chris Sarandon',
  'James Hong',
  'Catherine Chan',
  'Robert John Burke',
  'Anson Mount',
  'Reggie Lee',
  'Joseph Sikora',
  'Igor Jijikine',
  'Elissa Middleton',
  'Jack Gwaltney',
  'Barry Bradford',
  'Jay Giannone',
  'Laurence Covington',
  "Matt O'Toole"],
 ['Dustin Hoffman',
  'Rene Russo',
  'Morgan Freeman',
  'Kevin Spacey',
  'Cuba Gooding Jr.',
  'Donald Sutherland',
  'Patrick Dempsey',
  'Benito Martinez',
  'Malick Bowens',
  'Zakes Mokae',
  'Bruce Jarchow',
  'Dale Dye',
  'Conrad Bachmann',
  'Susan Lee Hoffman'],
 ['Charlton Heston',
  'Richard Harris',
  'Jim Hutton',
  'James Coburn',
  'Michael Anderson Jr.',
  'Senta Berger',
  'Mario Adorf',
  'Brock Peters',
  'Warren Oates',
  'Ben Johnson',
  'R. G. Armstrong',
  'Slim Pickens',
  'Karl Swenson',
  'Michael Pate'],
 ['Paul Newman',
  'George Kennedy',
  'Luke Askew',
  'Morgan Woodward',
  'Harry Dean Stanton',
  'Dennis Hopper',
  'Lou Antonio',
  'Robert Drivas',
  'Strother Martin',
  'Jo Van Fleet',
  'Clifton James',
  'Marc Cavell',
  'Richard Davalos',
  'Robert Donner',
  'J. D. Cannon',
  'Joe Don Baker',
  'James Gammon',
  'Chuck Hicks',
  'Rance Howard',
  'James Jeter',
  'Joy Harmon',
  'Anthony Zerbe',
  'Warren Finnerty',
  'John McLiam',
  'Wayne Rogers',
  'Charles Tyner',
  'Ralph Waite',
  'Buck Kartalian',
  'Kim Kahana',
  'Donn Pearce',
  'John Pearce',
  'Rush Williams'],
 ['Madonna',
  'Rupert Everett',
  'Benjamin Bratt',
  'Malcolm Stumpf',
  'Josef Sommer',
  'Suzanne Krull',
  'Linda Larkin',
  'Illeana Douglas',
  'Michael Vartan',
  'Lynn Redgrave',
  'Neil Patrick Harris'],
 ['Morgan Freeman',
  'Diane Keaton',
  'Carrie Preston',
  'Cynthia Nixon',
  'Alysia Reiner',
  'Josh Pais',
  'Claire van der Boom',
  'Sterling Jerins',
  'Liza J. Bennett',
  'Gary Wilmes',
  'Joanna Adler',
  'Jimmy Palumbo',
  'Hani Furstenberg',
  'Eric Sheffer Stevens',
  'Hannah Dunne',
  'Grace Rex',
  'Maddie Corman',
  'Miriam Shor',
  'Jackie Hoffman',
  'Jordan Baker',
  'Violet Krumbein',
  'Nadia Gan',
  'Jack Dimich',
  'Ilana Levine',
  'Katrina E. Perkins',
  'Anjili Pal',
  'Marcia DeBonis',
  'Henry Kelemen',
  'Diane Ciesla',
  'Jane Fergus',
  'Ted Sod',
  'Gregg Micheals'],
 ['Debra Messing',
  'Dermot Mulroney',
  'Amy Adams',
  'Jack Davenport',
  'Jeremy Sheffield',
  'Peter Egan',
  'Sarah Parish',
  'Holland Taylor',
  'Jay Simon',
  'Danielle Lewis'],
 ['Kseniya Rappoport',
  'Filippo Timi',
  'Antonia Truppo',
  'Gaetano Bruno',
  'Fausto Russo Alesi',
  'Michele Di Mauro',
  'Lorenzo Gioielli',
  'Lidia Vitale',
  'Giampiero Judica',
  'Roberto Accornero',
  'Lucia Poli',
  'Giorgio Colangeli',
  'Deborah Bernuzzi',
  'Barbara Braconi',
  'Federica Cassini'],
 ['Ray Romano',
  'John Leguizamo',
  'Denis Leary',
  'Queen Latifah',
  'Seann William Scott',
  'Josh Peck',
  'Jay Leno',
  'Will Arnett',
  'Chris Wedge',
  'Peter Ackerman',
  'Caitlin Rose Anderson',
  'Connor Anderson',
  'Joseph Bologna',
  'Jack Crocicchia',
  'Peter DeSeve',
  'Ariel Winter',
  'Clea Lewis',
  'Stephen Root',
  'Nicole DeFelice',
  'Debi Derryberry',
  'Marshall Efron',
  'Tom Fahn',
  'Jason Fricchione',
  'James Edmund Godwin',
  'George Jacobs',
  'Brian Scott McFadden',
  'Jansen Panettiere',
  'Gregory Romano',
  'Matthew Romano',
  'Carlos Saldanha',
  'Manoela Scarpa Saldanha',
  'Sofia Scarpa Saldanha',
  'Reyna Shaskan',
  'James Sie',
  'Cindy Slattery',
  'Mindy Sterling',
  'Alex Sullivan',
  'Ren√©e Taylor',
  'Alan Tudyk',
  'Claudia Besso',
  'Jess Harnell',
  'Madeleine Martin'],
 ['Samuel L. Jackson',
  'Kurt Russell',
  'Jennifer Jason Leigh',
  'Walton Goggins',
  'Demi√°n Bichir',
  'Tim Roth',
  'Michael Madsen',
  'Bruce Dern',
  'James Parks',
  'Dana Gourrier',
  'Zo√´ Bell',
  'Lee Horsley',
  'Gene Jones',
  'Keith Jefferson',
  'Craig Stark',
  'Belinda Owino',
  'Channing Tatum',
  'Quentin Tarantino'],
 ['Patrick Stewart',
  'Jonathan Frakes',
  'Brent Spiner',
  'LeVar Burton',
  'Michael Dorn',
  'Gates McFadden',
  'Marina Sirtis',
  'William Shatner',
  'James Doohan',
  'Walter Koenig',
  'Malcolm McDowell',
  'Alan Ruck',
  'Whoopi Goldberg',
  'Thomas Dekker',
  'Cameron Oppenheimer',
  'Jenette Goldstein',
  'Tim Russ'],
 ['Barbara Sarafian',
  'Jurgen Delnaet',
  'Johan Heldenbergh',
  'Anemone Valcke',
  'Sofia Ferri',
  'Julian Borsani',
  'Bob De Moor',
  'Jits Van Belle',
  'Griet van Damme'],
 ['Jack Lemmon',
  'Tony Curtis',
  'Natalie Wood',
  'Peter Falk',
  'Keenan Wynn',
  "Arthur O'Connell",
  'Vivian Vance',
  'Dorothy Provine',
  'Larry Storch',
  'Ross Martin',
  'George Macready',
  'Marvin Kaplan',
  'Hal Smith',
  'Denver Pyle',
  'William Bryant',
  'Hal Needham',
  'Raoul Retzer'],
 ['Tom Felton',
  'Cliff Curtis',
  'Joseph Fiennes',
  'Peter Firth',
  'Mark Killeen',
  'Mish Boyko',
  'Selva Rasalingam',
  'Stewart Scudamore',
  'Mar√≠a Botto',
  'Antonio Gil',
  'Stephen Hagan',
  'Stephen Greif',
  'Andy Gathergood',
  'Jovan Pisani',
  'Luis Callejo',
  'Jan Cornet',
  'Pepe Lorente',
  'Manu Fullola',
  'Mario Tard√≥n',
  '√Älex Maruny',
  'Paco Manzanedo',
  'Tom√°s Pozzi',
  'Karim Saleh',
  'Jacob Yakob',
  'Mario de la Rosa',
  'Ramiro Alonso',
  'Clare Agius',
  'Margaret Jackman',
  'Beppe Abela',
  'Manolo Caro'],
 ['George Clooney',
  "Chris O'Donnell",
  'Arnold Schwarzenegger',
  'Uma Thurman',
  'Alicia Silverstone',
  'Michael Gough',
  'Pat Hingle',
  'Elle Macpherson',
  'John Glover',
  'Vivica A. Fox',
  'Robert Swenson',
  'Coolio',
  'Jesse Ventura',
  'Ralf Moeller'],
 ['Ice Cube',
  'Mike Epps',
  'Tommy Flanagan',
  'Carmen Chaplin',
  'Eva Mendes',
  'Roger Guenveur Smith',
  'Oscar Isaac'],
 ['Daniel Craig',
  'Eva Green',
  'Mads Mikkelsen',
  'Judi Dench',
  'Jeffrey Wright',
  'Giancarlo Giannini',
  'Caterina Murino',
  'Simon Abkarian',
  'Isaach De Bankol√©',
  'Jesper Christensen',
  'Ivana Miliƒçeviƒá',
  'Tobias Menzies',
  'Claudio Santamaria',
  'Sebastien Foucan',
  'Malcolm Sinclair',
  'Richard Sammel',
  'Ludger Pistor',
  'Joseph Millson',
  'Darwin Shaw',
  'Clemens Schick',
  'Emmanuel Avena',
  'Tom Chadbon',
  'Ade',
  'Urbano Barberini',
  'Tsai Chin',
  'Lazar Ristovski',
  'Veruschka von Lehndorff',
  'Charlie Levi Leroy',
  'Tom So',
  'Andreas Daniel',
  'Carlos Leal',
  'Christina Cole',
  'J√ºrgen Tarrach',
  'John Gold',
  'Jerry Inzerillo',
  'Diane Hartford',
  'Jessica Miller',
  'Leo Stransky',
  'Paul Bhattacharjee',
  'Crispin Bonham-Carter',
  'Simon Cox',
  'Rebecca Gethings',
  'Peter Notley',
  'John Chancer',
  'Peter Brooke',
  'Jason Durran',
  'Robert Jezek',
  'Robert G. Slade',
  'F√©licit√© Du Jeu',
  'Michaela Ochotsk√°',
  'Michael Offei',
  'Makhoudia Diaw',
  'Michael G. Wilson',
  'Martina Duravol√°',
  'Marcela Martinc√°kov√°',
  'Vladimir Kulhavy',
  'Valentine Nonyela',
  'Dusan Pelech',
  'Phil Meheux',
  'Alessandra Ambrosio',
  'Veronika Hladikova',
  'Regina Gabajov√°',
  'Olutunji Ebun-Cole',
  'Martin Uc√≠k',
  'Vlastina Sv√°tkov√°',
  'Miroslav ≈†im≈Ønek',
  "Ivan G'Vera",
  'Jir√≠ Lenc',
  'Jaroslav Jankovsky',
  'Lasco Atkins',
  'Richard Branson',
  'Martin Campbell',
  'Tara Cardinal',
  'Ben Cooke',
  'Nigel Pilkington',
  'Simona Roman',
  'Victor Sobchak',
  'Valarie Trapp',
  'Greg Bennett'],
 ['Burt Lancaster',
  'Tony Curtis',
  'Gina Lollobrigida',
  'Katy Jurado',
  'Thomas Gomez',
  'Johnny Puleo',
  'Minor Watson',
  'G√©rard Landry',
  'Jean-Pierre K√©rien',
  'Sid James',
  'Gimma Boys',
  'Los Arriolas',
  'Gamil Ratib',
  'Pierre Tabard',
  'Edward Hagopian'],
 ['Kane Hodder',
  'Jensen Daggett',
  'Scott Reeves',
  'Barbara Bingham',
  'Peter Mark Richman',
  'Martin Cummins',
  'Gordon Currie',
  'Alex Diakun',
  'Vincent Craig Dupree',
  'Saffron Henderson',
  'Kelly Hu',
  'Sharlene Martin',
  'Todd Caldecott',
  'Tiffany Paulsen',
  'Tim Mirkovich',
  'Warren Munson'],
 ['Bruce Dern',
  'Will Forte',
  'Bob Odenkirk',
  'June Squibb',
  'Stacy Keach',
  'Missy Doty',
  'Rance Howard',
  'Kevin Kunkel',
  'Angela McEwan',
  'Devin Ratray',
  'Mary Louise Wilson',
  'Franklin Dennis Jones',
  'Anthony G. Schmidt',
  'Bob Nelson'],
 ['Jean-Claude Van Damme',
  'Bolo Yeung',
  'Roy Chiao',
  'Philip Chan Yan-Kin',
  'Donald Gibb',
  'Ken Siu',
  'Leah Ayres',
  'Norman Burton',
  'Forest Whitaker'],
 ['Keanu Reeves',
  'Vera Farmiga',
  'James Caan',
  'Judy Greer',
  'Fisher Stevens',
  'Danny Hoch',
  'Bill Duke',
  'Peter Stormare',
  'Currie Graham',
  'David Costabile',
  'Jordan Gelber',
  'Audrey Lynn Weston',
  'Julie Ordon',
  'Guy Boyd',
  'Peter Appel',
  'David Bishins'],
 ['Gregory Peck',
  'Brock Peters',
  'James Anderson',
  'Mary Badham',
  'Phillip Alford',
  'John Megna',
  'Estelle Evans',
  'Collin Wilcox Paxton',
  'Frank Overton',
  'Rosemary Murphy',
  'Ruth White',
  'Robert Duvall',
  'Paul Fix',
  'Alice Ghostley',
  'William Windom',
  'Crahan Denton',
  'Richard Hale',
  'R.L. Armstrong',
  'Eddie Baker',
  'Bobby Barber',
  'Danny Borzage',
  'John Breen',
  'Jess Cavin',
  'Steve Condit',
  'David Crawford',
  'Frank Ellis',
  'Charles Fredericks',
  'Herman Hack',
  'Jester Hairston',
  'Chuck Hamilton',
  'Kim Hamilton',
  'Michael Jeffers',
  'Dick Johnstone',
  'Colin Kenny',
  'Ethan Laidlaw',
  'Nancy Marshall',
  'Charles Morton',
  'Paulene Myers',
  "William H. O'Brien",

In [169]:
director5=[]
for i in range(len(df5['crew'])):
  l=[]
  for j in range(len(df5['crew'].iloc[i])):
    job=df5['crew'].iloc[i][j]["job"]
    if('director' in job.lower()):
      l.append(df5['crew'].iloc[i][j]["name"])
  director5.append(l)

In [170]:
director5

[['Kelly Cantley', 'Steve Pink', 'Declan Quinn', 'Josh King'],
 ['Garry Marshall', 'Charles Minsky'],
 ['Sharone Meir', 'Damien Chazelle', 'Nicolas Duchemin Harvard'],
 ['Sujoy Ghosh'],
 ['Hal Sutherland'],
 ['Ole Bornedal', 'Dan Laustsen', 'Randy Hutniak'],
 ['Christopher Guest', 'Arlene Nelson'],
 ['Steve Perry', 'Fred T. Gallo', 'James Crabe', 'John G. Avildsen'],
 ['Sam Mendes',
  'Conrad L. Hall',
  'Catherine Smith',
  'Tony Adler',
  'Rosemary C. Cremona'],
 ['Jeffrey L. Kimball', 'F. Gary Gray'],
 ['Steven Spielberg',
  'Janusz Kami≈Ñski',
  'Chris Gorak',
  'Jeffrey Mossa',
  'Pete Romano',
  'Sergio Mimica-Gezzan',
  'David H. Venghaus Jr.'],
 ['Stevan Filipoviƒá', 'Mihajlo Savic'],
 ['Wes Craven', 'Robert D. Yeoman'],
 ['Phil Traill'],
 ['Louis Leterrier', 'Mitchell Amundsen', 'Mehdi Sayah', 'Fabrice Bismuth'],
 ['Stephen Hopkins',
  'Peter Levy',
  'Keith Pain',
  'Chris Carreras',
  'Cliff Lanning',
  'Robert Grayson'],
 ['Steve Miner', 'Steve Miner', 'Gerald Feil'],
 ['David Mamet', 'Gabriel Beristain'],
 ['Michael Dowse', 'Rogier Stoffers'],
 ['Nelson Shin', 'Masatoshi Fukui'],
 ['Roger Michell', 'Salvatore Totino'],
 ['Mathieu Vadepied',
  'Eric Toledano',
  'Olivier Nakache',
  'Gabriel Botcherby',
  'Ma√´lys Deschard',
  'Charles Rempenault'],
 ['Dean Semler', 'Breck Eisner'],
 ['James Muro', 'Brett Ratner'],
 ['Stefan Czapsky', 'Boaz Yakin'],
 ['Wolfgang Petersen', 'Michael Ballhaus'],
 ['Sam Leavitt', 'Sam Peckinpah'],
 ['Conrad L. Hall', 'Hank Moonjean', 'Stuart Rosenberg'],
 ['John Schlesinger', 'Elliot Davis'],
 ['Richard Loncraine', 'Jonathan Freeman'],
 ['Clare Kilner'],
 ['Giuseppe Capotondi', 'Tat Radcliffe'],
 ['Carlos Saldanha'],
 ['Quentin Tarantino', 'Robert Richardson', 'Kil Won Yu'],
 ['David Carson', 'John A. Alonzo'],
 ['Christophe Van Rompaey'],
 ['Blake Edwards', 'Russell Harlan'],
 ['Kevin Reynolds', 'Lorenzo Senatore'],
 ['Joel Schumacher',
  'Stephen Goldblatt',
  'William M. Elvin',
  'Richard Holland',
  'Charlie Daboub'],
 ['Kevin Bray'],
 ['Martin Campbell',
  'Phil Meheux',
  'Bruce Moriarty',
  'Simon Lamont',
  'Peter Dorme',
  'Guy Bradley',
  'Molly Sole',
  'Consuelo Bidorini',
  'Lorenzo Marangoni',
  'Lisa Romano',
  'Jakub Dvorak'],
 ['Robert Krasker', 'Carol Reed'],
 ['Rob Hedden', 'Bryan England'],
 ['Alexander Payne', 'Phedon Papamichael', 'George Parra'],
 ['Newt Arnold', 'David Worth'],
 ['Paul Cameron', 'Malcolm Venville'],
 ['Robert Mulligan', 'Russell Harlan', 'Joseph E. Kenney', 'Terry Morse, Jr.'],
 ['Justin Lin', 'Stephen F. Windon'],
 ['Peter Deming', 'John Maybury'],
 ['John Waters', 'David Insley'],
 ['Michael Miller', 'Bruce Logan'],
 ['Craig Gillespie'],
 ['Rajiv Menon'],
 ['Harold Ramis', 'Stevan Larner'],
 ['Rob Zombie', 'David Daniel'],
 ['Ron Shelton', 'Barry Peterson'],
 ['Peter Suschitzky', 'Anand Tucker'],
 ['Iain Softley',
  'Daniel Mindel',
  'Jann Engel',
  'Phil Pastuhov',
  'Gary Marcus'],
 ['Peter Hyams', 'Peter Hyams'],
 ['Chris Kentis', 'Laura Lau'],
 ['Frank Marshall', 'Allen Daviau'],
 ['Robert Benton',
  'N√©stor Almendros',
  'Thomas John Kane',
  'Ira Halberstadt',
  'Lewis Gould'],
 ['Stanley Tong'],
 ['Niki Caro', 'Andrij Parekh'],
 ['Quentin Tarantino',
  'Robert Richardson',
  'Katsuhito Ishii',
  'Satoko Saito',
  'Kennedy Taylor',
  'Jonathan Tex Levitt',
  'Texas Dave'],
 ['Thierry Arbogast', 'Jean-Paul Rappeneau'],
 ['David Lynch', 'Peter Deming'],
 ['Tom Stern', 'Fr√©d√©ric Jardin'],
 ['Enrique Gato'],
 ['Dennis Hopper', 'Haskell Wexler'],
 ['Mark Irwin', 'Craig R. Baxley'],
 ['Ron Howard', 'Roger Deakins', 'Bradley Mayer', 'Nancy Winters'],
 ['Ben Smithard', 'Luke Hull', 'Amma Asante', 'Ben Smith'],
 ['Andrew Dunn', 'Tom Vaughan'],
 ['Mel Gibson',
  'John Toll',
  'Daniel T. Dorrance',
  'Clare Langan',
  "Padraig O'Neill",
  'Anna Rackard',
  'Brendan Rankin'],
 ['Oliver Parker'],
 ['Russell Harlan', 'George Roy Hill'],
 ['Barry Levinson', 'Josh McLaglen', 'Dante Spinotti', 'Kurt E. Soderling'],
 ['Theo van de Sande', 'Nick Hurran'],
 ['Ron Howard',
  'Anthony Dod Mantle',
  'James Collins',
  'Isabel G√≥mez-Blanco',
  'Christian Huband',
  'Niall Moroney'],
 ['Mike Nichols', 'Bill Butler'],
 ['Peter Jackson', 'Andrew Lesnie'],
 ['Malcolm D. Lee', 'Tom Priestley Jr.'],
 ['Sammo Hung', 'Raymond Lam'],
 ['Matthew F. Leonetti', 'Brett Ratner'],
 ['Kevin Lima', 'Chris Buck'],
 ['Colin D. Irwin', 'Bob Clark', 'Reginald H. Morris'],
 ['Andrzej Bartkowiak', 'Glen MacPherson'],
 ['Eric Steelberg', 'Marc Webb'],
 ['Roger Spottiswoode', 'Zhao Xiaoding'],
 ['Sam Raimi', 'Jamie Anderson', 'C. Scott Baker'],
 ['Rupert Wainwright', 'Nathan Hope'],
 ['Spike Lee'],
 ['Declan Lowney', 'Ben Smithard'],
 ['Lance Daly'],
 ['Shepherd Frankel', 'Lawrence Sher', 'Todd Phillips'],
 ['David Schwimmer'],
 ['Ian Jones', 'Rolf de Heer', 'Peter Djigirr'],
 ['Hart Bochner',
  'Reynaldo Villalobos',
  'Martin Walters',
  'Walter Gasparovic'],
 ['Bryan Singer', 'Newton Thomas Sigel', 'Geoff Hubbard'],
 ['Robert Wise', 'Ernest Laszlo'],
 ['Bryan Buckley', 'Scott Henriksen'],
 ['Gregor Jordan'],
 ['Terence Young', 'Charles Lang', 'Jack Aldworth'],
 ['Bong Joon-ho', 'Kyung-Pyo Hong', 'Jakub Dvorak'],
 ['John Stockwell',
  'Florian Friedmann',
  'Tom Hannam',
  'Jean-Fran√ßois Hensgens'],
 ['Rob Cohen', 'David McFarland'],
 ['Robin Budd', 'Donovan Cook'],
 ['Aleksei Sidorov'],
 ['Stephen T. Kay', 'Mauro Fiore', 'Kevin Fair'],
 ['Sam Raimi', 'Dante Spinotti'],
 ['Adam Rapp'],
 ['Lynn Shelton', 'Benjamin Kasulke'],
 ['Wes Anderson', 'Robert D. Yeoman'],
 ['Stephen Hopkins', 'Peter Levy'],
 ['Tom Stern', 'Scott Derrickson', 'Kendelle Elliott'],
 ['Blake Edwards', 'Geoffrey Unsworth', 'Bert Batt', 'Guy Sauteret'],
 ['Dean Semler', 'George Miller'],
 ['Conrad L. Hall', 'James H. Brown', 'Jack Smight'],
 ['Robert Steadman', 'William A. Graham'],
 ['Stephan Elliott'],
 ['Rob Cohen',
  'Ericson Core',
  'Lars P. Winther',
  'Rebecca Marie',
  'Michael Stone'],
 ['Walter Hill', 'Lloyd Ahern II', 'Scott Meehan', 'Jack Sholder'],
 ['Ted Kotcheff',
  'Andrew Laszlo',
  'Craig Huston',
  'Otta Hanus',
  'Jacques Hubert'],
 ['John Glen', 'Alec Mills'],
 ['Declan Quinn', "Gavin O'Connor"],
 ['Takashi Miike'],
 ['Dean Semler', 'Frank Coraci'],
 ['Richard A. Colla'],
 ['Mike Clattenburg'],
 ['Tod Browning', 'Percy Hilburn'],
 ['Andrew Stanton', 'Jeremy Lasky'],
 ['Gerry Lively', 'Kevin Yagher', 'Joe Chappelle'],
 ['Xavier Grobet', 'Kirk Jones'],
 ['Edward Lachman', 'Todd Solondz'],
 ['Armand Mastroianni'],
 ['Gabriel Beristain', 'Clark Johnson'],
 ['Brian Robbins'],
 ['Micha√´l R. Roskam', 'Nicolas Karakatsanis', 'Dan-ah Kim', 'Ryan Palmer'],
 ['Seamus McGarvey', 'Gary Winick'],
 ['Oliver Stapleton', 'Julien Temple'],
 ['Jimmy Hayward'],
 ['David Silverman', 'Gary McCarver', 'Matthew Schofield'],
 ['Howard Storm'],
 ['Jerry Jameson', 'Luis David Sansans'],
 ['Paul Murphy', 'Bryan Spicer'],
 ['Joe Johnston',
  'Shelly Johnson',
  'Troy Sizemore',
  'William M. Elvin',
  'Patricio M. Farrell',
  'Hans Bjerno',
  'Yann Mari Faget',
  'Tarik Ait Ben Ali',
  'Jae Cheol Hong'],
 ['Egon Werdin', 'Anthony Waller'],
 ['Steven Spielberg',
  'Bill Butler',
  'Barbara Bass',
  'Tom Joyner',
  'L. Andrew Stone'],
 ['Prabhu Deva', 'Santosh Thundiiayil'],
 ['Ariel Vromen', 'Bobby Bukowski'],
 ['Javier Aguirresarobe', 'Seth Gordon'],
 ['Takashi Yamazaki', 'Ry≈´ichi Yagi'],
 ['Ivan Reitman', 'Bill Butler'],
 ['Stacy Peralta', 'Peter Pilafian'],
 ['Lu Chuan', 'Yu Cao'],
 ['Masanobu Takayanagi', 'Keith Bearden'],
 ['Jan de Bont', 'Paul Verhoeven'],
 ['Patrick Lussier', 'Brian Pearson', 'Simeon Asenov'],
 ['Lone Scherfig', 'John de Borman'],
 ['Sam Peckinpah', 'Lucien Ballard', 'Clifford C. Coleman'],
 ['James Ivory'],
 ['Phil Meheux',
  'Sarah Horton',
  'Frank Coraci',
  'Gary Freeman',
  'Adam Dale',
  'Nick Heckstall-Smith',
  'George Walker',
  'Paul Goldsmith'],
 ['Victor Nunez', 'Alex Vlacos', 'Jennifer Fong'],
 ['James Gray', 'Darius Khondji', 'Adam Dale'],
 ['Gilbert Adler', 'Tom Priestley Jr.'],
 ['Adam Greenberg', 'Jerry Zucker', 'Doug Chiang'],
 ['Charles Stone III'],
 ['Dan St. Pierre', 'Dougg Williams'],
 ['Tim Orr', 'Sean Anders'],
 ['Chuck Russell', 'John R. Leonetti'],
 ['Rainer Klausmann',
  'Oliver Hirschbiegel',
  'Bohdan Graczyk',
  'Aleksey Filatov',
  'Sergey Fukalov',
  'Hanus Polak Jr.'],
 ['Dominic Sena', 'Paul Cameron'],
 ['Jack Cardiff', 'John Guillermin'],
 ['Thomas Gilou'],
 ['Peter Levy', 'Renny Harlin'],
 ['Lawrence Sher',
  'Jay Chandrasekhar',
  'Fernando Altschul',
  'Francisco Ramirez',
  'Brett Hool'],
 ['Jun Lana', 'Carlo Mendoza'],
 ['Jason Bateman'],
 ['Baltasar Korm√°kur',
  'Salvatore Totino',
  'Tom Still',
  'Gianpaolo Rifino',
  'Ed Symon'],
 ['Leo Tover', 'Robert D. Webb', 'Stanley Hough'],
 ['Santosh Sivan'],
 ['Barry Sonnenfeld', 'Fred Murphy'],
 ['Jacques Haitkin', 'Steve De Jarnatt'],
 ['Rodrigo Prieto', 'Spike Lee'],
 ['Sean Penn', 'Eric Gautier', 'John R. Saunders', 'David Webb'],
 ['Kevin Smith', 'David Klein'],
 ['Chris Seager', 'Geoffrey Sax'],
 ['David Bowers'],
 ['Oliver Wood', 'Adam McKay'],
 ['Ric Waite', 'Dwight H. Little'],
 ['Greg Gardiner', 'Tom Dey'],
 ['Nora Ephron', 'John Lindley'],
 ['Kodi Rama Krishna', 'K.K. Senthil Kumar'],
 ['Michael Chapman', 'Ivan Reitman', 'David F. Klassen'],
 ['Michael Mann',
  'Dion Beebe',
  'Aran Mann',
  'Paul Cameron',
  'Gerald Sullivan',
  'Christopher Tandon',
  'Michael Waxman'],
 ['Peter Deming', 'Drew Goddard', 'Tom Reta', 'Chris Grun'],
 ['John Bailey', 'Richard LaGravenese'],
 ['C√©dric Klapisch', 'Christophe Beaucarne'],
 ['David Ayer', 'Roman Vasyanov'],
 ['Mac Ahlberg', 'Stuart Gordon'],
 ['M. Night Shyamalan',
  'Nicole Agostino',
  'Amy Lauritsen',
  'John Rusk',
  'Mike Gioulakis'],
 ['Reggie Rock Bythewood', 'Greg Gardiner'],
 ['Gary Goldman', 'Don Bluth', 'Dave Kupczyk'],
 ['Mike Newell', 'Michael Coulter'],
 ['Scott Frank', 'Scott Frank', 'Alar Kivilo'],
 ['Roger Deakins',
  'Joseph P. Reidy',
  'Charlie Revai',
  'Angelina Jolie',
  'Simon Christidis'],
 ['Francis Lawrence',
  'Dan Webster',
  'Jo Willems',
  'David Scheunemann',
  'Shaun Friedberg',
  'Carine Demongueres',
  'Sean Ryan Jennings',
  'Alice Leconte',
  "Justin O'Neal Miller",
  'Jade Mansueto',
  'Marlene Chazot',
  'Gunnar Zimmer'],
 ['Tom Shadyac', 'Dean Semler', 'Sally Thornton', 'Dawn Swiderski'],
 ['Andrzej Bartkowiak', 'Daryn Okada'],
 ['Fred Murphy', 'Paul Mazursky'],
 ['Ate de Jong', 'Robin Vidgeon'],
 ['Ron Underwood', 'Alexander Gruszynski'],
 ['Wesley Ruggles'],
 ['Martin Scorsese', 'Michael Ballhaus'],
 ['Spike Jonze'],
 ['Ben Affleck', 'Robert Richardson', 'Christa Munro', 'Bradley Rubin'],
 ['Shane Hurlbut', 'Charles Stone III'],
 ['Oliver Wood', 'Mark Waters'],
 ['Paul Sarossy', 'Atom Egoyan'],
 ['Xavier Dolan', 'Yves B√©langer'],
 ['Lance Rivera'],
 ['Brian Fee', 'Jeremy Lasky', 'Newton Thomas Sigel'],
 ['Clint Eastwood', 'Tom Stern', 'Donald Murphy'],
 ['Peter Lord', 'Jeff Newitt'],
 ['Catherine Ircha',
  'Neill Blomkamp',
  'Don MacAulay',
  'Trent Opaloch',
  'Luis Antonio Ordo√±ez',
  'Kent Matheson'],
 ['Shusuke Kaneko'],
 ['Peter Weir', 'John Seale'],
 ['Brendan Galvin', 'Tarsem Singh'],
 ['Alejandro Gonz√°lez I√±√°rritu',
  'Emmanuel Lubezki',
  'Isabelle Guay',
  'Michael Diner',
  'Chris Beach'],
 ['Brian Helgeland', 'Ericson Core', 'Mark Cotone'],
 ['Robert Benton'],
 ['Betty Thomas', 'Russell Boyd'],
 ['Donald E. Thorin',
  'Hugh Wilson',
  'Ed Check',
  'Paul D. Kelly',
  'Michael E. Steele',
  'Julie A. Bloom'],
 ['Olivier Megaton',
  'Romain Lacourbas',
  'Patrick Pasquier',
  'Sandro Valdez',
  'Anne Pelosi',
  'Eva Julhe'],
 ['Shana Feste'],
 ['George Miller',
  'Judy Morris',
  'Warren Coleman',
  'David Peers',
  'David Nelson',
  'P.J. Voeten',
  'Daniel Jeannette',
  'Brad Greenwood'],
 ['Teddy Chan'],
 ['Peter Lyons Collister', 'Bernie Goldmann', 'Melisa Wallack'],
 ['Craig Gillespie'],
 ['Larry Fong', 'Louis Leterrier', 'Mitchell Amundsen'],
 ['Danny Cannon', 'Michael Barrett'],
 ['James Wong Howe', 'Martin Ritt', 'James A. Rosenberger'],
 ['Gary Fleder', 'Aaron Schneider'],
 ['Kenneth Branagh', 'Stuart Kearns', 'Haris Zambarloukos'],
 ['David Frankel', 'Maryse Alberti'],
 ['Hayao Miyazaki',
  'Shigeharu Shiba',
  'Kazuyoshi Katayama',
  'Kazuo Komatsubara',
  'Takashi Tanazawa'],
 ['Zana Briski', 'Ross Kauffman'],
 ['Enrique Chediak',
  'Marc Fisichella',
  'Peter Berg',
  'Brittany Loar',
  'Lauren Slatten'],
 ['Guy Hamilton', 'Ted Moore'],
 ['DJ Pooh'],
 ['Lexi Alexander',
  'Vincent Gingras-Liberali',
  'Charlotte Rouleau',
  'Guy Pigeon'],
 ['Seamus McGarvey',
  'Breck Eisner',
  'Marc Homes',
  'John Marzano',
  'Christopher Newman'],
 ['Roger Allers', 'Rob Minkoff'],
 ['Paul W.S. Anderson', 'David Tattersall', 'Paul Sonski', 'Melanie J. Baker'],
 ['Peter Jackson', 'Andrew Lesnie'],
 ['Hari', 'Priyan'],
 ['Renat Davletyarov', 'Semyon Yakovlev'],
 ['Jacques Audiard', 'St√©phane Fontaine'],
 ['Michael Mann',
  'Dante Spinotti',
  'Margie Stone McShirley',
  'Erik Olson',
  'Steven Schwartz',
  'Michael Waxman'],
 ['Randall Wallace', 'Dean Semler'],
 ['David Gelb', 'Michael Fimognari'],
 ['Anees Bazmee'],
 ['John Moore', 'Patrick Lumb', 'Brendan Galvin'],
 ['Martin Scorsese', 'Michael Ballhaus'],
 ["John 'Bud' Cardos", 'John Arthur Morrill'],
 ['Stephen Goldblatt', 'Peter Hyams'],
 ['Norton Virgien', 'Igor Kovalyov'],
 ['Joel Coen', 'Barry Sonnenfeld', 'Gregory Jacobs'],
 ['Gary Chapman'],
 ['Edward Zwick',
  'Eduardo Serra',
  'Peter Wenham',
  'Ray Chan',
  'Sarah Moudjebeur'],
 ['Jean-Jacques Annaud', 'Jean-Marie Dreujou'],
 ['John Dahl', 'Marc Reshovsky'],
 ['Oliver Stone', 'Salvatore Totino'],
 ['Steve Bendelack', 'Baz Irvine'],
 ['Hector Babenco', 'Lauro Escorel'],
 ['Steve Gainer', 'Mike Gunther'],
 ['Donald McAlpine', 'Peter Segal'],
 ['Alessandro Genovesi'],
 ['Dmitriy Kiselev'],
 ['Brian Levant', 'Victor J. Kemper'],
 ['Michael C. Butler', 'Hal Needham'],
 ['Michael Mann',
  'Dante Spinotti',
  'Dennis Bradford',
  'Erik Olson',
  'Patricia Woodbridge'],
 ['John Waters', 'Robert M. Stevens'],
 ['John Bailey', 'Gary David Goldberg'],
 ['Rajkumar Santoshi', 'A.R. Rahman'],
 ['Jim Gillespie', 'Denis Crossan', 'Steve Mirkovich', "Louis D'Esposito"],
 ['John A. Alonzo', 'Ralph Bakshi'],
 ['Robert Richardson', 'Oliver Stone', 'Seth Cirker'],
 ['Tim Suhrstedt', 'Stephen Herek'],
 ['James Cameron', 'Adrian Biddle', 'Terry Ackland-Snow'],
 ['Gary Ross', 'John Schwartzman', 'Michael Scheffe'],
 ['Lasse Hallstr√∂m', 'Terry Stacey'],
 ['Martin Koolhoven'],
 ['Larry Charles'],
 ['Simon West', 'Peter Menzies Jr.'],
 ['Elliot Davis', 'Catherine Hardwicke'],
 ['Ashwani Dhir', 'Tushar Hiranandani'],
 ['Woody Allen', 'Darius Khondji', 'Sid Karne', 'Gil Kenny'],
 ['Andrew Laszlo', 'Brian Gibson', 'John Bruno'],
 ['Scott Sanders'],
 ['James McTeigue', 'Frank Walsh', 'Danny Ruhlmann'],
 ['Anthony Byrne'],
 ['Fred Savage'],
 ['Peter Weir', 'Russell Boyd'],
 ['Christopher Nolan', 'Wally Pfister', 'Alan B. Curtiss'],
 ['Richard Linklater', 'Shane F. Kelly'],
 ['Matthew F. Leonetti',
  'Lon Bender',
  'Eric Bress',
  'J. Mackye Gruber',
  'Geoffrey G. Rubay',
  'Peter D. Marshall',
  'Cindy Smith',
  'Lori K. Peterson'],
 ['Kathryn Bigelow', 'Adrian Biddle'],
 ['Gore Verbinski', 'Dariusz Wolski'],
 ['M. David Mullen', 'Michael Polish'],
 ['Remi Adefarasin', 'Peter Howitt'],
 ['Ron Shelton', 'Bobby Byrne'],
 ['Kleber Mendon√ßa Filho', 'Pedro Sotero', 'Fabricio Tadeu\t'],
 ['Simon Duggan', 'Sue Chan', 'Noam Murro'],
 ['Nicole Garcia', 'Christophe Beaucarne', 'S√©bastien Matuchet'],
 ['Peter Hyams', 'John Hyams'],
 ['Andrew Lesnie', 'Chris Noonan'],
 ['Peter Kohn',
  'Michael Ballhaus',
  'Wolfgang Petersen',
  'Nancy Patton',
  'David B. Nowell'],
 ['Peter Hyams', 'Peter Hyams'],
 ['Ashley Rowe', 'Andy Cadiff'],
 ['Anthony Hickox', 'Gerry Lively'],
 ['Alfred Hitchcock', 'George Barnes', 'Edmond F. Bernoudy', 'Eric Stacey'],
 ['Tom Kalin'],
 ['Kirk Jones'],
 ['Robert Rodriguez', 'Guillermo Navarro'],
 ['Greg Gardiner', 'Andy Fickman'],
 ['Robert Zemeckis',
  'Don Burgess',
  'Doug J. Meerdink',
  'Sally Thornton',
  'Brad Ricker',
  'Bruce Moriarty',
  'Martin A. Kline'],
 ['Patrick Read Johnson'],
 ['Sylvester Stallone', 'Bill Butler'],
 ['Mark Irwin', 'Joe Nussbaum'],
 ['Christophe Beaucarne', 'Anne Fontaine'],
 ['Lawrence Sher', 'Todd Phillips'],
 ['John Lindley', 'Joseph Ruben'],
 ['Stefan Ruzowitzky'],
 ['Inna Evlannikova', 'Svyatoslav Ushakov'],
 ['Howard Deutch'],
 ['Lorene Scafaria', 'Brett Pawlak'],
 ['David Eggby', 'John Bonito'],
 ['Himman Dhamija', 'Nikhil Advani'],
 ['Miroslav Ond≈ô√≠ƒçek', 'Penny Marshall'],
 ['Roland Emmerich', 'Markus F√∂rderer'],
 ['Robert Redford',
  'Newton Thomas Sigel',
  'Geoffrey S. Grimsman',
  'Alex Laurent'],
 ['Robert Redford', 'Robert Richardson'],
 ['Ilya Maksimov'],
 ['James DeMonaco', 'Jacques Jouffret'],
 ['Todd Haynes'],
 ['Adam Elliot', 'Gerald Thompson'],
 ['Philippe Rousselot', 'Robert Redford'],
 ['Stefan Ruzowitzky', 'Shane Hurlbut', 'F√©lix Larivi√®re-Charron'],
 ['Anders Anderson'],
 ['David Hogan'],
 ['Justin Barber', 'Jay Keitel'],
 ['Mark Irwin', 'Kevin Hooks'],
 ['Genndy Tartakovsky'],
 ['John Toll', 'Cameron Crowe'],
 ['Spike Lee'],
 ['St√©phane Rybojad'],
 ['Barry Levinson', 'St√©phane Fontaine'],
 ['Stuart Baird',
  'Andrzej Bartkowiak',
  'Kurt E. Soderling',
  'David W. Krummel',
  'Vincent Lascoumes'],
 ['Darren Aronofsky', 'Matthew Libatique'],
 ['Gr√©gory Levasseur', 'Laurent Tangy', 'Heidi El Ayoubi'],
 ['Elia Kazan', 'Boris Kaufman'],
 ['Lasse Hallstr√∂m', 'Terry Stacey'],
 ['Peter Hyams', 'Peter Hyams'],
 ['David Koepp', 'Fred Murphy'],
 ['Mani Ratnam', 'P. C. Sreeram'],
 ['James Marsh',
  'Beno√Æt Delhomme',
  'Kira Kemble',
  'Deborah Saban',
  'David Hindle'],
 ['Paul Thomas Anderson', 'Mihai Malaimare Jr.', 'Adam Somner'],
 ['Peter Howitt', 'John Bailey'],
 ['Tim Burton', 'Bruno Delbonnel'],
 ['Michael D. Moore',
  'Cecil B. DeMille',
  'Loyal Griggs',
  'Daniel McCauley',
  'Francisco Day',
  'Edward Salven'],
 ['Julian Gilbey', 'Ali Asad'],
 ['Thomas Bezucha', 'Jonathan Brown'],
 ['Peter Deming', 'Marco Schnabel'],
 ['Robert Elswit', 'Tony Gilroy', 'Steve Apicella'],
 ['Dean Semler', 'Donald Petrie'],
 ['Henry Koster', 'Leon Shamroy'],
 ['Harry Winer'],
 ['Gyula Pados',
  'Nimr√≥d Antal',
  'Sean Noel Walker',
  'Brian Bettwy',
  'jonathan Swartz'],
 ['Rod Hardy', 'David Connell'],
 ['Matthew Libatique', 'Spike Lee'],
 ['Martin Lawrence', 'Daryn Okada', 'David Raynr'],
 ['Michael Bay', 'John Schwartzman'],
 ['Steven Spielberg', 'Douglas Slocombe', 'Artist W. Robinson'],
 ['Joe Wright', 'John Mathieson', 'Seamus McGarvey'],
 ['Richard Linklater', 'Lee Daniel'],
 ['Danny Cannon', 'Vernon Layton', 'Enrique Echeverr√≠a', "Louis D'Esposito"],
 ['Peter Jackson', 'Andrew Lesnie'],
 ['Bob Fosse', 'Robert Surtees'],
 ['Christian Sebaldt', 'Preston A. Whitmore II', 'Regina Gordon'],
 ['Alexander Payne', 'James Glennon'],
 ['John Harrison', 'Robert Draper'],
 ['Mike Flanagan'],
 ['Matthew Libatique', 'Joel Schumacher'],
 ['Neill Blomkamp', 'Trent Opaloch'],
 ['Mathieu Kassovitz',
  'Matthew Libatique',
  'Nicolas Lepage',
  'Jim Kaufman',
  'Pete Romano',
  'Pierre Brassard',
  'Nadine Brassard'],
 ['Rintaro', 'Hitoshi Yamaguchi'],
 ['Anastas N. Michos', 'David E. Talbert'],
 ['Dexter Fletcher'],
 ['Carroll Ballard', 'Caleb Deschanel'],
 ['Jack Green',
  'Donald B. Woodruff',
  'Peter Segal',
  'Hans Bjerno',
  'Laura Weiss',
  'Adam Druxman',
  'Joseph J. Kontra'],
 ['Karen Schulz Gropman', 'John Frankish', 'John Wells', 'Adriano Goldman'],
 ['John Wayne', 'William H. Clothier'],
 ['James Whitaker', 'Julie Anne Robinson'],
 ['Denise Di Novi',
  'Caleb Deschanel',
  'Jonas Spaccarotelli',
  'Ravi D. Mehta',
  'Steven Ritzi',
  'Deborah Chung'],
 ['Marshall Brickman', 'Billy Williams'],
 ['Anthony Dod Mantle', 'Danny Boyle', 'Mark Digby'],
 ['Rob Zombie',
  'Tom Richmond',
  'Alex Poppas',
  'Erin Smith',
  'Marco Black',
  'Ty Arnold'],
 ['Martin Campbell', 'Phil Meheux', 'Greg Berry', 'Ron Mason'],

In [171]:
df5['ROI']=pd.DataFrame((df5['revenue']-df5['budget'])/df5['budget'],columns=['ROI'])

In [172]:
df5['director']=director5
df5['actor']=actor5

In [173]:
table5=pd.DataFrame({"director":df5['director'],"actor":df5['actor'],"ROI":df5['ROI']})

In [174]:
table5

,director,actor,ROI
0,"[Kelly Cantley, Steve Pink, Declan Quinn, Josh...","[Rob Corddry, Craig Robinson, Clark Duke, Adam...",-0.120382
1,"[Garry Marshall, Charles Minsky]","[Anne Hathaway, Julie Andrews, H√©ctor Elizond...",1.378736
2,"[Sharone Meir, Damien Chazelle, Nicolas Duchem...","[Miles Teller, J.K. Simmons, Melissa Benoist, ...",2.967273
3,[Sujoy Ghosh],"[Vidya Balan, Nawazuddin Siddiqui, Parambrata ...",12.333333
5,[Hal Sutherland],"[Scott Grimes, Tom Bosley, Rickie Lee Jones, J...",-0.592295
...,...,...,...
2976,"[Arthur Edeson, Raoul Walsh, James T. O'Donoho...","[Douglas Fairbanks, Snitz Edwards, Charles Bel...",0.068882
2977,"[Steven Spielberg, Janusz Kami≈Ñski]","[Tom Hanks, Catherine Zeta-Jones, Stanley Tucc...",2.656954
2981,"[Renny Harlin, Guillermo Navarro]","[Geena Davis, Samuel L. Jackson, Yvonne Zima, ...",0.376258
2982,"[Seamus McGarvey, John Hamburg, Daniel Silverb...","[Ben Stiller, Jennifer Aniston, Philip Seymour...",3.094366
2983,"[John Singleton, Peter Menzies Jr., Jay Durrwa...","[Taylor Lautner, Lily Collins, Alfred Molina, ...",1.345347

In [175]:
table5=table5.explode("director")

In [176]:
table5=table5.explode("actor")

In [177]:
table5

             director                    actor       ROI
0       Kelly Cantley              Rob Corddry -0.120382
0       Kelly Cantley           Craig Robinson -0.120382
0       Kelly Cantley               Clark Duke -0.120382
0       Kelly Cantley               Adam Scott -0.120382
0       Kelly Cantley              Chevy Chase -0.120382
...               ...                      ...       ...
2983  Jay Durrwachter               Jack Erdie  1.345347
2983  Jay Durrwachter              Steve Blass  1.345347
2983  Jay Durrwachter            Derek Burnell  1.345347
2983  Jay Durrwachter  Tiffany Sander McKenzie  1.345347
2983  Jay Durrwachter         Joanna Theobalds  1.345347

[142600 rows x 3 columns]

In [178]:
top_directors=table5.groupby('director')['ROI'].mean().sort_values(ascending=False).head(3)

In [179]:
top_directors

director
Oren Peli           12889.386667
Daniel Myrick        4132.333333
Eduardo S√°nchez     4132.333333
Name: ROI, dtype: float64

In [180]:
top_actors_of_top_directors=table5[table5['director'].isin(top_directors.index)].groupby(['director','actor']).size().sort_values(ascending=False)

In [181]:
top_actors_of_top_directors

director          actor
Oren Peli         Ashley Palmer          2
                  Micah Sloat            2
                  Mark Fredrichs         2
                  Katie Featherston      2
                  Amber Armstrong        2
Daniel Myrick     Ed Swanson             1
                  Heather Donahue        1
                  Jackie Hallex          1
                  Bob Griffith           1
                  Patricia DeCou         1
                  Michael C. Williams    1
                  Mark Mason             1
                  Joshua Leonard         1
                  Jim King               1
                  Sandra S√°nchez        1
Eduardo S√°nchez  Ed Swanson             1
                  Bob Griffith           1
                  Mark Mason             1
                  Joshua Leonard         1
                  Jim King               1
                  Jackie Hallex          1
                  Heather Donahue        1
                  Sandra S√°nchez        1
                  Michael C. Williams    1
                  Patricia DeCou         1
dtype: int64

#question 6: which actor has acted in the most number of movies? deep dive into the movies,genres and profits corresponding to this actor.

In [182]:
data.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
runtime                     2
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
dtype: int64

In [183]:
df6=data.dropna(subset=['genres','cast']).reset_index(drop=True)

In [184]:
df6

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2975,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2976,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2977,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2978,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2979,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [185]:
df6=df6[df6['budget']>10000]

In [186]:
df6['profit']=pd.DataFrame((df6['revenue']-df6['budget']),columns=['ROI'])

/tmp/ipykernel_109539/3244727004.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['profit']=pd.DataFrame((df6['revenue']-df6['budget']),columns=['ROI'])

In [187]:
df6['cast']=df6['cast'].apply(convert)

/tmp/ipykernel_109539/2206595126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['cast']=df6['cast'].apply(convert)

In [188]:
df6['cast'][0]

[{'cast_id': 4,
  'character': 'Lou',
  'credit_id': '52fe4ee7c3a36847f82afae7',
  'gender': 2,
  'id': 52997,
  'name': 'Rob Corddry',
  'order': 0,
  'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'},
 {'cast_id': 5,
  'character': 'Nick',
  'credit_id': '52fe4ee7c3a36847f82afaeb',
  'gender': 2,
  'id': 64342,
  'name': 'Craig Robinson',
  'order': 1,
  'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'},
 {'cast_id': 6,
  'character': 'Jacob',
  'credit_id': '52fe4ee7c3a36847f82afaef',
  'gender': 2,
  'id': 54729,
  'name': 'Clark Duke',
  'order': 2,
  'profile_path': '/oNzK0umwm5Wn0wyEbOy6TVJCSBn.jpg'},
 {'cast_id': 7,
  'character': 'Adam Jr.',
  'credit_id': '52fe4ee7c3a36847f82afaf3',
  'gender': 2,
  'id': 36801,
  'name': 'Adam Scott',
  'order': 3,
  'profile_path': '/5gb65xz8bzd42yjMAl4zwo4cvKw.jpg'},
 {'cast_id': 8,
  'character': 'Hot Tub Repairman',
  'credit_id': '52fe4ee7c3a36847f82afaf7',
  'gender': 2,
  'id': 54812,
  'name': 'Chevy Chase',
  'order': 4,
  'profile_path': '/svjpyYtPwtjvRxX9IZnOmOkhDOt.jpg'},
 {'cast_id': 9,
  'character': 'Jill',
  'credit_id': '52fe4ee7c3a36847f82afafb',
  'gender': 1,
  'id': 94098,
  'name': 'Gillian Jacobs',
  'order': 5,
  'profile_path': '/rBnhe5vhNPnhRUdtYahBWx90fJM.jpg'},
 {'cast_id': 10,
  'character': 'Sophie',
  'credit_id': '52fe4ee7c3a36847f82afaff',
  'gender': 1,
  'id': 1159009,
  'name': 'Bianca Haase',
  'order': 6,
  'profile_path': '/4x3nbtD8q8phAJPmoGWXPvz0iM.jpg'},
 {'cast_id': 11,
  'character': 'Kelly',
  'credit_id': '5524ec51c3a3687df3000dbb',
  'gender': 1,
  'id': 86624,
  'name': 'Collette Wolfe',
  'order': 7,
  'profile_path': '/aSD4h5379b2eEw3bLou9ByLimmq.jpg'},
 {'cast_id': 13,
  'character': 'Brad',
  'credit_id': '5524ec8ec3a3687ded000d72',
  'gender': 2,
  'id': 466505,
  'name': 'Kumail Nanjiani',
  'order': 9,
  'profile_path': '/x4nAztHY72SVciRfxEsbhIVTsIu.jpg'},
 {'cast_id': 14,
  'character': 'Courtney',
  'credit_id': '5524ec9bc3a3687df8000d13',
  'gender': 1,
  'id': 70776,
  'name': 'Kellee Stewart',
  'order': 10,
  'profile_path': '/w3xmsEPmJc1Cf0dQ4aIn8YmlHbk.jpg'},
 {'cast_id': 15,
  'character': 'Terry',
  'credit_id': '5524eca892514171cb008237',
  'gender': 2,
  'id': 347335,
  'name': 'Josh Heald',
  'order': 11,
  'profile_path': '/pwXJIenrDMrG7t3zNfLvr8w1RGU.jpg'},
 {'cast_id': 16,
  'character': 'Susan',
  'credit_id': '5524ecb7925141720c001116',
  'gender': 0,
  'id': 1451392,
  'name': 'Gretchen Koerner',
  'order': 12,
  'profile_path': '/muULPexCTJGyJba4yKzxronpD50.jpg'},
 {'cast_id': 17,
  'character': 'Herself',
  'credit_id': '5524ecc3c3a3687ded000d74',
  'gender': 1,
  'id': 98879,
  'name': 'Lisa Loeb',
  'order': 13,
  'profile_path': '/bGqg58ca0bZR38z9HliUMmeNGE.jpg'},
 {'cast_id': 18,
  'character': 'Herself',
  'credit_id': '5524ecd3c3a3687e11000ed3',
  'gender': 1,
  'id': 1394648,
  'name': 'Jessica Williams',
  'order': 14,
  'profile_path': '/A4syKjkcYB92wLEhH0c0hC3BCpz.jpg'},
 {'cast_id': 19,
  'character': 'Himself',
  'credit_id': '5524ece6925141718d001009',
  'gender': 0,
  'id': 1451393,
  'name': 'Bruce Buffer',
  'order': 15,
  'profile_path': None},
 {'cast_id': 20,
  'character': 'Shot Girl',
  'credit_id': '5524ecf5c3a3687e08000dc2',
  'gender': 0,
  'id': 1451394,
  'name': 'Mariana Paola Vicente',
  'order': 16,
  'profile_path': '/ckPllza8624UHWGHCbLShkLxCD1.jpg'},
 {'cast_id': 33,
  'character': 'Choozy Doozy Host',
  'credit_id': '555844da9251412afe0013a9',
  'gender': 2,
  'id': 2224,
  'name': 'Christian Slater',
  'order': 17,
  'profile_path': '/3ElLWjnvchMS6Q4cIQOK8QNAoMG.jpg'},
 {'cast_id': 35,
  'character': 'Gary Winkle',
  'credit_id': '55872027c3a3683853005074',
  'gender': 0,
  'id': 185805,
  'name': 'Jason Jones',
  'order': 18,
  'profile_path': '/aIoCw6vo8AGMdsQRAI5g2t0yJT3.jpg'},
 {'cast_id': 36,
  'character': 'Bridesmaid',
  'credit_id': '55efe971c3a368090c00cd1b',
  'gender': 0,
  'id': 1507448,
  'name': 'Olivia Jordan',
  'order': 19,
  'profile_path': '/szMukAEiIDeasel0lvyaeyKuych.jpg'},
 {'cast_id': 37,
  'character': 'Christine',
  'credit_id': '55efe980c3a36871bf008176',
  'gender': 1,
  'id': 1334091,
  'name': 'Christine Bently',
  'order': 20,
  'profile_path': '/oUZltnGa55OXE52hfyPTfCshuNy.jpg'},
 {'cast_id': 38,
  'character': 'Excited Girl',
  'credit_id': '55efe98e9251413e3201d316',
  'gender': 0,
  'id': 557803,
  'name': 'Stacey Asaro',
  'order': 21,
  'profile_path': '/qTPdlr1dXf3kNdyHuDsgtGC0HCC.jpg'},
 {'cast_id': 64,
  'character': 'Adam (uncredited)',
  'credit_id': '58f2135ac3a3682e95008b91',
  'gender': 2,
  'id': 3036,
  'name': 'John Cusack',
  'order': 22,
  'profile_path': '/uKydQYuZ9TnCzvbQLtj6j98vWAT.jpg'},
 {'cast_id': 65,
  'character': 'J-Bird',
  'credit_id': '59ac0240c3a3682cc802c399',
  'gender': 2,
  'id': 59256,
  'name': 'Adam Herschman',
  'order': 23,
  'profile_path': '/wZMwiuX1DslF6hDS50z9OTN6z1X.jpg'},
 {'cast_id': 66,
  'character': 'Bridesmaid',
  'credit_id': '59ac02cd925141079d02b1b4',
  'gender': 1,
  'id': 129714,
  'name': 'Kisha Sierra',
  'order': 24,
  'profile_path': None}]

In [189]:
actor=[]
for i in range(len(df6["cast"])):
  l=[]
  for j in range(len(df6["cast"].iloc[i])):
    l.append(df6["cast"].iloc[i][j]["name"])
  actor.append(l)

In [190]:
df6["actor"]=actor

/tmp/ipykernel_109539/1889907981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6["actor"]=actor

In [191]:
df6['genres']=df6['genres'].apply(convert)

/tmp/ipykernel_109539/3763351045.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['genres']=df6['genres'].apply(convert)

In [192]:
df6['genres_name']=df6['genres'].apply(lambda x: [i['name'] for i in x] if(isinstance(x,list)) else None)

/tmp/ipykernel_109539/2766996420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['genres_name']=df6['genres'].apply(lambda x: [i['name'] for i in x] if(isinstance(x,list)) else None)

In [193]:
table6=df6[['actor','original_title','profit','genres_name']]

In [194]:
table6

,actor,original_title,profit,genres_name
0,"[Rob Corddry, Craig Robinson, Clark Duke, Adam...",Hot Tub Time Machine 2,-1685349,[Comedy]
1,"[Anne Hathaway, Julie Andrews, H√©ctor Elizond...",The Princess Diaries 2: Royal Engagement,55149435,"[Comedy, Drama, Family, Romance]"
2,"[Miles Teller, J.K. Simmons, Melissa Benoist, ...",Whiplash,9792000,[Drama]
3,"[Vidya Balan, Nawazuddin Siddiqui, Parambrata ...",Kahaani,14800000,"[Thriller, Drama]"
5,"[Scott Grimes, Tom Bosley, Rickie Lee Jones, J...",Pinocchio and the Emperor of the Night,-4738362,"[Animation, Adventure, Family]"
...,...,...,...,...
2972,"[Douglas Fairbanks, Snitz Edwards, Charles Bel...",The Thief of Bagdad,78226,"[Action, Adventure, Drama, Family, Fantasy]"
2973,"[Tom Hanks, Catherine Zeta-Jones, Stanley Tucc...",The Terminal,159417255,"[Comedy, Drama]"
2977,"[Geena Davis, Samuel L. Jackson, Yvonne Zima, ...",The Long Kiss Goodnight,24456761,"[Crime, Action, Mystery, Thriller]"
2978,"[Ben Stiller, Jennifer Aniston, Philip Seymour...",Along Came Polly,129963386,"[Comedy, Romance]"
2979,"[Taylor Lautner, Lily Collins, Alfred Molina, ...",Abduction,47087155,"[Thriller, Action, Mystery]"

In [195]:
table6=table6.explode('actor')

In [196]:
table6

,actor,original_title,profit,genres_name
0,Rob Corddry,Hot Tub Time Machine 2,-1685349,[Comedy]
0,Craig Robinson,Hot Tub Time Machine 2,-1685349,[Comedy]
0,Clark Duke,Hot Tub Time Machine 2,-1685349,[Comedy]
0,Adam Scott,Hot Tub Time Machine 2,-1685349,[Comedy]
0,Chevy Chase,Hot Tub Time Machine 2,-1685349,[Comedy]
...,...,...,...,...
2979,Jack Erdie,Abduction,47087155,"[Thriller, Action, Mystery]"
2979,Steve Blass,Abduction,47087155,"[Thriller, Action, Mystery]"
2979,Derek Burnell,Abduction,47087155,"[Thriller, Action, Mystery]"
2979,Tiffany Sander McKenzie,Abduction,47087155,"[Thriller, Action, Mystery]"
2979,Joanna Theobalds,Abduction,47087155,"[Thriller, Action, Mystery]"

In [197]:
actors_movie=table6.groupby('actor')['original_title'].nunique()

In [198]:
actors_movie.sort_values(ascending=False)

actor
Samuel L. Jackson     25
Robert De Niro        24
Bruce McGill          23
Morgan Freeman        23
J.K. Simmons          23
                      ..
A. Michael Baldwin     1
A. Jay Radcliff        1
A. J. Langer           1
A. David Burleigh      1
A Martinez             1
Name: original_title, Length: 31736, dtype: int64

In [199]:
top_actor=actors_movie.idxmax()

In [200]:
table_top_actor=table6[table6['actor']==top_actor].reset_index(drop=True)

In [201]:
table_top_actor

,actor,original_title,profit,genres_name
0,Samuel L. Jackson,Changing Lanes,49935764,"[Action, Adventure, Crime, Thriller]"
1,Samuel L. Jackson,The Hateful Eight,111760117,"[Crime, Drama, Mystery, Western]"
2,Samuel L. Jackson,Coming to America,249752301,"[Comedy, Romance]"
3,Samuel L. Jackson,Star Wars: Episode III - Revenge of the Sith,737000000,"[Science Fiction, Adventure, Action]"
4,Samuel L. Jackson,The Avengers,1299557910,"[Science Fiction, Action, Adventure]"
5,Samuel L. Jackson,Jumper,137231186,"[Adventure, Fantasy, Science Fiction]"
6,Samuel L. Jackson,Shaft,61196498,"[Action, Adventure, Crime, Thriller]"
7,Samuel L. Jackson,Snakes on a Plane,29022014,"[Action, Crime, Horror, Thriller]"
8,Samuel L. Jackson,RoboCop,122688965,"[Action, Science Fiction]"
9,Samuel L. Jackson,Jurassic Park,857100000,"[Adventure, Science Fiction]"
10,Samuel L. Jackson,Star Wars: Episode II - Attack of the Clones,529398328,"[Adventure, Action, Science Fiction]"
11,Samuel L. Jackson,Captain America: The Winter Soldier,544766572,"[Action, Adventure, Science Fiction]"
12,Samuel L. Jackson,Jackie Brown,27673162,"[Comedy, Crime, Romance]"
13,Samuel L. Jackson,Big Game,-1000000,"[Action, Adventure, Thriller]"
14,Samuel L. Jackson,Black Snake Moan,-4096154,[Drama]
15,Samuel L. Jackson,Sea of Love,91879513,"[Drama, Crime, Mystery]"
16,Samuel L. Jackson,Deep Blue Sea,13648228,"[Action, Science Fiction, Thriller]"
17,Samuel L. Jackson,Basic,-7207439,"[Action, Drama, Mystery, Thriller, Crime]"
18,Samuel L. Jackson,The Incredibles,539442092,"[Action, Adventure, Animation, Family]"
19,Samuel L. Jackson,Avengers: Age of Ultron,1125403694,"[Action, Adventure, Science Fiction]"
20,Samuel L. Jackson,Out of Sight,29745568,"[Romance, Comedy, Crime]"
21,Samuel L. Jackson,Patriot Games,133051587,"[Drama, Action, Thriller, Crime]"
22,Samuel L. Jackson,S.W.A.T.,36643346,"[Action, Thriller, Crime]"
23,Samuel L. Jackson,Freedomland,-23009372,"[Drama, Thriller, Crime, Mystery]"
24,Samuel L. Jackson,The Long Kiss Goodnight,24456761,"[Crime, Action, Mystery, Thriller]"

In [202]:
top_actor_movie=[]
top_actor_genres=set()
profit=0
for i in range(len(table_top_actor)):
  top_actor_movie.append(table_top_actor["original_title"][i])
  profit+=table_top_actor['profit'][i]
  for j in range(len(table_top_actor['genres_name'][i])):
    top_actor_genres.add(table_top_actor['genres_name'][i][j])

In [203]:
#top actor
top_actor

'Samuel L. Jackson'

In [204]:
#top actor's movies
top_actor_movie

['Changing Lanes',
 'The Hateful Eight',
 'Coming to America',
 'Star Wars: Episode III - Revenge of the Sith',
 'The Avengers',
 'Jumper',
 'Shaft',
 'Snakes on a Plane',
 'RoboCop',
 'Jurassic Park',
 'Star Wars: Episode II - Attack of the Clones',
 'Captain America: The Winter Soldier',
 'Jackie Brown',
 'Big Game',
 'Black Snake Moan',
 'Sea of Love',
 'Deep Blue Sea',
 'Basic',
 'The Incredibles',
 'Avengers: Age of Ultron',
 'Out of Sight',
 'Patriot Games',
 'S.W.A.T.',
 'Freedomland',
 'The Long Kiss Goodnight']

In [205]:
#top actor's profit
print(profit)

6716040641

In [206]:
#top actor's genres
list(top_actor_genres)

['Science Fiction',
 'Action',
 'Mystery',
 'Romance',
 'Thriller',
 'Crime',
 'Fantasy',
 'Family',
 'Adventure',
 'Horror',
 'Comedy',
 'Animation',
 'Drama',
 'Western']